package mechanist.assets;

/**
 * Quality tiers generated by the 0.9.10kc source-first art rebase.
 * This enum is deliberately independent from the legacy semantic registry so the
 * resolver bridge can be introduced without forcing old IDs to change first.
 */
public enum AssetQualityTier {
    HIGH_NATIVE("high_native"),
    INTERMEDIATE_128("intermediate_128"),
    STANDARD_64("standard_64"),
    LOW_32("low_32");

    private final String directoryName;

    AssetQualityTier(String directoryName) {
        this.directoryName = directoryName;
    }

    public String directoryName() {
        return directoryName;
    }

    public static AssetQualityTier fromToken(String token) {
        if (token == null || token.isBlank()) return LOW_32;
        String normalized = token.trim().toLowerCase().replace('-', '_');
        for (AssetQualityTier tier : values()) {
            if (tier.directoryName.equals(normalized) || tier.name().toLowerCase().equals(normalized)) {
                return tier;
            }
        }
        return LOW_32;
    }
}
