#!/usr/bin/env python3
"""
split_game_panel.py

One-run GamePanel shard splitter for The Mechanist.

This is an executable refactor tool, not a pre-commit hook and not a
documentation-only plan. It preserves the GamePanel class as the stable public
surface while moving selected method bodies into same-package subsystem classes
and routing GamePanel wrappers through a generated GamePanelSubsystemIndex.

Run from repository root:

    py -3 ROOT_tools/refactor/split_game_panel.py --apply

Useful inspection run:

    py -3 ROOT_tools/refactor/split_game_panel.py --dry-run --verbose

The script intentionally refuses to run if it cannot identify the GamePanel
class, method boundaries, or a sane same-package Java source folder.
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple


ROOT = Path.cwd()
PREFERRED_GAME_PANEL_PATHS = (
    Path("src/mechanist/GamePanel.java"),
    Path("PACKAGE_client/src/main/java/mechanist/GamePanel.java"),
    Path("PACKAGE_client/src/mechanist/GamePanel.java"),
)
GENERATED_HEADER = (
    "// AUTO-GENERATED by ROOT_tools/refactor/split_game_panel.py.\n"
    "// Do not hand-edit generated GamePanel subsystem files; rerun the splitter.\n\n"
)
INDEX_CLASS = "GamePanelSubsystemIndex"
INDEX_FIELD = "gamePanelModules"

CONTROL_WORDS = {
    "if", "for", "while", "switch", "catch", "try", "else", "do", "return",
    "new", "case", "default", "throw", "throws", "synchronized", "assert",
}

JAVA_KEYWORDS = {
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char",
    "class", "const", "continue", "default", "do", "double", "else", "enum",
    "extends", "final", "finally", "float", "for", "goto", "if", "implements",
    "import", "instanceof", "int", "interface", "long", "native", "new",
    "package", "private", "protected", "public", "return", "short", "static",
    "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while", "var", "record", "sealed",
    "permits", "non-sealed",
}

MODIFIER_WORDS = {
    "public", "private", "protected", "static", "final", "synchronized",
    "abstract", "native", "strictfp", "transient", "volatile", "default",
}


SUBSYSTEM_RULES: Tuple[Tuple[str, str, Sequence[str]], ...] = (
    ("Render", "GamePanelRenderSubsystem", (
        "paint", "draw", "render", "graphics", "hud", "overlay", "crt", "screen",
        "surface", "sprite", "tile", "camera", "viewport", "menu", "font", "color",
    )),
    ("Input", "GamePanelInputSubsystem", (
        "key", "mouse", "wheel", "click", "drag", "input", "route", "button",
        "command", "shortcut", "controller", "scroll", "focus",
    )),
    ("Options", "GamePanelOptionsSubsystem", (
        "option", "setting", "volume", "sound", "music", "graphics", "scale",
        "quality", "display", "accessibility", "doom", "saveOptions", "loadOptions",
    )),
    ("World", "GamePanelWorldSubsystem", (
        "world", "zone", "sector", "room", "road", "plaza", "atlas", "map",
        "generation", "terrain", "spawn", "transition", "audit",
    )),
    ("Simulation", "GamePanelSimulationSubsystem", (
        "tick", "turn", "advance", "update", "simulation", "npc", "entity",
        "population", "faction", "heat", "suspicion", "path", "move", "movement",
    )),
    ("Combat", "GamePanelCombatSubsystem", (
        "combat", "attack", "damage", "weapon", "armor", "hit", "wound",
        "target", "hostile", "enemy", "corpse",
    )),
    ("Inventory", "GamePanelInventorySubsystem", (
        "inventory", "item", "loot", "container", "trade", "buy", "sell",
        "equip", "equipment", "stock", "cargo", "craft", "recipe",
    )),
    ("Persistence", "GamePanelPersistenceSubsystem", (
        "save", "load", "storage", "profile", "persist", "autosave", "export",
        "import", "serialize", "deserialize",
    )),
    ("Audio", "GamePanelAudioSubsystem", (
        "audio", "sound", "music", "clip", "play", "mute", "volume", "track",
    )),
    ("Diagnostic", "GamePanelDiagnosticSubsystem", (
        "debug", "diagnostic", "audit", "smoke", "verify", "report", "log",
        "trace", "dump", "inspect",
    )),
    ("Runtime", "GamePanelRuntimeSubsystem", (
        "init", "start", "stop", "reset", "timer", "loop", "runtime", "frame",
        "dispose", "shutdown", "launch", "boot",
    )),
)


@dataclasses.dataclass(frozen=True)
class ClassBounds:
    name: str
    decl_start: int
    body_start: int
    body_end: int


@dataclasses.dataclass(frozen=True)
class Param:
    declaration: str
    name: str


@dataclasses.dataclass
class Member:
    kind: str
    name: str
    start: int
    end: int
    header_start: int
    body_start: int
    body_end: int
    header: str
    body: str
    return_type: str = ""
    params: List[Param] = dataclasses.field(default_factory=list)
    modifiers: Set[str] = dataclasses.field(default_factory=set)
    annotations: str = ""
    signature_prefix: str = ""
    is_static: bool = False
    is_private: bool = False
    subsystem_class: str = ""
    subsystem_label: str = ""


@dataclasses.dataclass(frozen=True)
class RewriteReport:
    game_panel: str
    generated_files: List[str]
    moved_methods: int
    relaxed_private_members: int
    source_sha256_before: str
    source_sha256_after: str


def die(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(2)


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def strip_comments_and_literals(src: str) -> str:
    out: List[str] = []
    i = 0
    n = len(src)
    state = "normal"
    while i < n:
        ch = src[i]
        nxt = src[i + 1] if i + 1 < n else ""

        if state == "normal":
            if ch == "/" and nxt == "/":
                out.append(" ")
                out.append(" ")
                i += 2
                state = "line_comment"
                continue
            if ch == "/" and nxt == "*":
                out.append(" ")
                out.append(" ")
                i += 2
                state = "block_comment"
                continue
            if ch == '"':
                out.append(" ")
                i += 1
                state = "string"
                continue
            if ch == "'":
                out.append(" ")
                i += 1
                state = "char"
                continue
            out.append(ch)
            i += 1
            continue

        if state == "line_comment":
            out.append("\n" if ch == "\n" else " ")
            i += 1
            if ch == "\n":
                state = "normal"
            continue

        if state == "block_comment":
            if ch == "*" and nxt == "/":
                out.append(" ")
                out.append(" ")
                i += 2
                state = "normal"
            else:
                out.append("\n" if ch == "\n" else " ")
                i += 1
            continue

        if state == "string":
            if ch == "\\":
                out.append(" ")
                if i + 1 < n:
                    out.append("\n" if src[i + 1] == "\n" else " ")
                i += 2
                continue
            out.append("\n" if ch == "\n" else " ")
            i += 1
            if ch == '"':
                state = "normal"
            continue

        if state == "char":
            if ch == "\\":
                out.append(" ")
                if i + 1 < n:
                    out.append("\n" if src[i + 1] == "\n" else " ")
                i += 2
                continue
            out.append("\n" if ch == "\n" else " ")
            i += 1
            if ch == "'":
                state = "normal"
            continue

    return "".join(out)


def build_depth_maps(clean: str) -> List[int]:
    depth_at: List[int] = [0] * (len(clean) + 1)
    depth = 0
    for i, ch in enumerate(clean):
        depth_at[i] = depth
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth = max(0, depth - 1)
    depth_at[len(clean)] = depth
    return depth_at


def find_matching_brace(clean: str, open_pos: int) -> int:
    if open_pos < 0 or open_pos >= len(clean) or clean[open_pos] != "{":
        die(f"internal parser error: expected '{{' at {open_pos}")
    depth = 0
    for i in range(open_pos, len(clean)):
        if clean[i] == "{":
            depth += 1
        elif clean[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    die("unbalanced Java braces; refusing to rewrite")


def find_game_panel_class(src: str, clean: str) -> ClassBounds:
    pattern = re.compile(r"\b(?:public\s+|private\s+|protected\s+|abstract\s+|final\s+|static\s+)*class\s+GamePanel\b")
    match = pattern.search(clean)
    if not match:
        die("could not find `class GamePanel` in selected Java file")
    brace = clean.find("{", match.end())
    if brace < 0:
        die("could not find opening brace for class GamePanel")
    end = find_matching_brace(clean, brace)
    return ClassBounds("GamePanel", match.start(), brace, end)


def find_package(src: str) -> str:
    m = re.search(r"(?m)^\s*package\s+([A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)*)\s*;", src)
    return m.group(1) if m else ""


def find_import_block(src: str) -> str:
    imports = re.findall(r"(?m)^\s*import\s+[^;]+;", src)
    return "\n".join(imports).strip()


def line_start(src: str, pos: int) -> int:
    p = src.rfind("\n", 0, pos)
    return 0 if p < 0 else p + 1


def find_statement_start(src: str, clean: str, depth_at: Sequence[int], pos: int, class_depth: int) -> int:
    i = pos - 1
    while i >= 0:
        ch = clean[i]
        if depth_at[i] == class_depth and ch in ";{}":
            return line_start(src, i + 1)
        i -= 1
    return line_start(src, 0)


def collect_top_level_members(src: str, clean: str, bounds: ClassBounds) -> List[Tuple[int, int, str]]:
    depth_at = build_depth_maps(clean)
    class_depth = depth_at[bounds.body_start] + 1
    members: List[Tuple[int, int, str]] = []
    i = bounds.body_start + 1
    while i < bounds.body_end:
        if depth_at[i] != class_depth:
            i += 1
            continue
        ch = clean[i]
        if ch == "{":
            start = find_statement_start(src, clean, depth_at, i, class_depth)
            end = find_matching_brace(clean, i) + 1
            members.append((start, end, "block"))
            i = end
            continue
        if ch == ";":
            start = find_statement_start(src, clean, depth_at, i, class_depth)
            members.append((start, i + 1, "statement"))
            i += 1
            continue
        i += 1
    return normalize_member_ranges(members)


def normalize_member_ranges(ranges: List[Tuple[int, int, str]]) -> List[Tuple[int, int, str]]:
    if not ranges:
        return []
    ranges = sorted(ranges)
    normalized: List[Tuple[int, int, str]] = []
    for start, end, kind in ranges:
        if normalized and start < normalized[-1][1]:
            old_start, old_end, old_kind = normalized[-1]
            normalized[-1] = (old_start, max(old_end, end), old_kind if old_kind == "block" else kind)
        else:
            normalized.append((start, end, kind))
    return normalized


def parse_params(params_text: str) -> List[Param]:
    params_text = params_text.strip()
    if not params_text:
        return []
    parts = split_top_level_commas(params_text)
    params: List[Param] = []
    for raw in parts:
        decl = " ".join(raw.strip().split())
        if not decl:
            continue
        name = param_name_from_decl(decl)
        params.append(Param(declaration=decl, name=name))
    return params


def split_top_level_commas(text: str) -> List[str]:
    parts: List[str] = []
    start = 0
    angle = paren = bracket = 0
    for i, ch in enumerate(text):
        if ch == "<":
            angle += 1
        elif ch == ">":
            angle = max(0, angle - 1)
        elif ch == "(":
            paren += 1
        elif ch == ")":
            paren = max(0, paren - 1)
        elif ch == "[":
            bracket += 1
        elif ch == "]":
            bracket = max(0, bracket - 1)
        elif ch == "," and angle == 0 and paren == 0 and bracket == 0:
            parts.append(text[start:i])
            start = i + 1
    parts.append(text[start:])
    return parts


def param_name_from_decl(decl: str) -> str:
    clean_decl = re.sub(r"@\w+(?:\([^)]*\))?\s*", "", decl)
    clean_decl = clean_decl.replace(" final ", " ")
    tokens = re.findall(r"[A-Za-z_$][\w$]*", clean_decl)
    if not tokens:
        return ""
    return tokens[-1]


def strip_leading_annotations(header: str) -> Tuple[str, str]:
    lines = header.splitlines()
    annotation_lines: List[str] = []
    rest_lines: List[str] = []
    in_rest = False
    for line in lines:
        stripped = line.strip()
        if not in_rest and (not stripped or stripped.startswith("@")):
            annotation_lines.append(line)
        else:
            in_rest = True
            rest_lines.append(line)
    return "\n".join(annotation_lines).strip(), "\n".join(rest_lines).strip()


def parse_method_member(src: str, clean: str, member_range: Tuple[int, int, str]) -> Optional[Member]:
    start, end, range_kind = member_range
    if range_kind != "block":
        return None
    chunk = src[start:end]
    clean_chunk = clean[start:end]
    open_rel = clean_chunk.find("{")
    close_rel = len(chunk) - 1
    if open_rel < 0:
        return None

    header = chunk[:open_rel].rstrip()
    header_clean = clean_chunk[:open_rel].rstrip()
    if re.search(r"\b(?:class|interface|enum|record)\s+[A-Za-z_$][\w$]*", header_clean):
        return None

    sig_match = re.search(r"([A-Za-z_$][\w$]*)\s*\((.*)\)\s*(?:throws\s+[^{}]+)?\s*$", header_clean, re.S)
    if not sig_match:
        return None

    name = sig_match.group(1)
    if name in CONTROL_WORDS:
        return None

    before_name = header_clean[:sig_match.start(1)].strip()
    if not before_name:
        return None

    annotations, _signature_no_annotations = strip_leading_annotations(header)
    signature_clean = re.sub(r"\s+", " ", strip_leading_annotations(header_clean)[1]).strip()
    signature_no_annotations_clean = re.sub(r"\s+", " ", signature_clean)

    paren_start = signature_no_annotations_clean.rfind(f"{name}(")
    if paren_start < 0:
        paren_start = signature_no_annotations_clean.rfind(f"{name} (")
    prefix = signature_no_annotations_clean[:paren_start].strip() if paren_start >= 0 else before_name

    tokens = re.findall(r"[A-Za-z_$][\w$]*", prefix)
    modifiers = set(t for t in tokens if t in MODIFIER_WORDS)
    is_constructor = name == "GamePanel"
    if is_constructor:
        return None

    non_mod_tokens = [t for t in tokens if t not in MODIFIER_WORDS]
    if not non_mod_tokens and "void" not in prefix:
        return None

    return_type = infer_return_type(prefix)
    if not return_type:
        return None

    params_start = header_clean.rfind("(", 0, len(header_clean))
    params_end = header_clean.rfind(")")
    params = parse_params(header[params_start + 1:params_end] if params_start >= 0 and params_end >= 0 else "")

    body = chunk[open_rel + 1:close_rel]
    return Member(
        kind="method",
        name=name,
        start=start,
        end=end,
        header_start=start,
        body_start=start + open_rel,
        body_end=end - 1,
        header=header,
        body=body,
        return_type=return_type,
        params=params,
        modifiers=modifiers,
        annotations=annotations,
        signature_prefix=prefix,
        is_static="static" in modifiers,
        is_private="private" in modifiers,
    )


def infer_return_type(prefix: str) -> str:
    p = re.sub(r"\s+", " ", prefix.strip())
    if not p:
        return ""
    changed = True
    while changed:
        old = p
        p = re.sub(r"^(?:public|private|protected|static|final|synchronized|abstract|native|strictfp)\s+", "", p)
        changed = old != p
    if p.startswith("<"):
        gt = p.find(">")
        if gt >= 0:
            rest = p[gt + 1:].strip()
            if rest:
                return rest
    tokens = p.split()
    if not tokens:
        return ""
    return " ".join(tokens)


def classify_subsystem(method: Member) -> Tuple[str, str]:
    hay = method.name.lower()
    for label, class_name, words in SUBSYSTEM_RULES:
        if any(word.lower() in hay for word in words):
            return label, class_name
    return "Misc", "GamePanelMiscSubsystem"


def extract_field_names(src: str, clean: str, member_ranges: Sequence[Tuple[int, int, str]]) -> Set[str]:
    fields: Set[str] = set()
    for start, end, kind in member_ranges:
        if kind != "statement":
            continue
        chunk = src[start:end]
        clean_chunk = clean[start:end]
        if "(" in clean_chunk:
            continue
        if re.search(r"\b(?:class|interface|enum|record)\b", clean_chunk):
            continue
        fields.update(names_from_field_statement(chunk))
    return fields


def names_from_field_statement(statement: str) -> Set[str]:
    stmt = re.sub(r"//.*", "", statement)
    stmt = re.sub(r"/\*.*?\*/", " ", stmt, flags=re.S)
    stmt = stmt.strip().rstrip(";").strip()
    if not stmt:
        return set()
    if stmt.startswith("import ") or stmt.startswith("package "):
        return set()

    stmt = re.sub(r"^\s*(?:public|private|protected|static|final|transient|volatile)\s+", "", stmt)
    changed = True
    while changed:
        old = stmt
        stmt = re.sub(r"^\s*(?:public|private|protected|static|final|transient|volatile)\s+", "", stmt)
        changed = old != stmt

    parts = split_top_level_commas(stmt)
    if not parts:
        return set()
    names: Set[str] = set()
    first = parts[0]
    first_before_eq = first.split("=", 1)[0].strip()
    tokens = re.findall(r"[A-Za-z_$][\w$]*", first_before_eq)
    if len(tokens) >= 2:
        names.add(tokens[-1])
    for extra in parts[1:]:
        before_eq = extra.split("=", 1)[0].strip()
        tokens = re.findall(r"[A-Za-z_$][\w$]*", before_eq)
        if tokens:
            names.add(tokens[-1])
    return {n for n in names if n not in JAVA_KEYWORDS}


def method_names(methods: Sequence[Member]) -> Set[str]:
    return {m.name for m in methods}


def collect_local_names(method: Member) -> Set[str]:
    locals_: Set[str] = {p.name for p in method.params if p.name}
    body = strip_comments_and_literals(method.body)

    patterns = [
        r"\b(?:final\s+)?(?:[A-Z_a-z$][\w$]*(?:\s*<[^;{}()]*>)?(?:\s*\[\])*)\s+([A-Za-z_$][\w$]*)\s*(?:=|;|,)",
        r"\bfor\s*\(\s*(?:final\s+)?(?:[A-Z_a-z$][\w$]*(?:\s*<[^;{}()]*>)?(?:\s*\[\])*)\s+([A-Za-z_$][\w$]*)\s*:",
        r"\bcatch\s*\(\s*(?:final\s+)?[A-Z_a-z$][\w$<>.?]*\s+([A-Za-z_$][\w$]*)\s*\)",
        r"\btry\s*\(\s*(?:final\s+)?[A-Z_a-z$][\w$<>.?]*\s+([A-Za-z_$][\w$]*)\s*=",
        r"\b([A-Za-z_$][\w$]*)\s*->",
    ]
    for pat in patterns:
        for m in re.finditer(pat, body):
            name = m.group(1)
            if name not in JAVA_KEYWORDS:
                locals_.add(name)
    return locals_


def should_prefix_identifier(text: str, start: int, end: int) -> bool:
    i = start - 1
    while i >= 0 and text[i].isspace():
        i -= 1
    if i >= 0 and text[i] in ".:":
        return False
    if i >= 0 and text[i] == "@":
        return False
    j = end
    while j < len(text) and text[j].isspace():
        j += 1
    if j < len(text) and text[j] == ":":
        return False
    return True


def rewrite_body_for_subsystem(
    method: Member,
    field_names: Set[str],
    game_panel_method_names: Set[str],
) -> str:
    text = method.body
    text = text.replace("this.", "self.")
    text = re.sub(r"\bthis\b", "self", text)

    locals_ = collect_local_names(method)

    target_fields = field_names - locals_
    target_methods = game_panel_method_names - {method.name}

    identifiers = sorted(target_fields | target_methods, key=len, reverse=True)
    if not identifiers:
        return text

    pattern = re.compile(r"\b(" + "|".join(re.escape(x) for x in identifiers) + r")\b")

    def repl(match: re.Match[str]) -> str:
        name = match.group(1)
        start, end = match.span(1)
        if not should_prefix_identifier(text, start, end):
            return name
        j = end
        while j < len(text) and text[j].isspace():
            j += 1
        is_call = j < len(text) and text[j] == "("
        if name in target_methods and is_call:
            return "self." + name
        if name in target_fields and not is_call:
            return "self." + name
        return name

    return pattern.sub(repl, text)


def remove_private_from_top_level_members(
    src: str,
    clean: str,
    bounds: ClassBounds,
    member_ranges: Sequence[Tuple[int, int, str]],
) -> Tuple[str, int]:
    edits: List[Tuple[int, int, str]] = []
    for start, end, _kind in member_ranges:
        if start < bounds.body_start or end > bounds.body_end:
            continue
        chunk_clean = clean[start:end]
        m = re.search(r"(?m)^(\s*)private\s+", chunk_clean)
        if not m:
            continue
        absolute_start = start + m.start(0) + len(m.group(1))
        absolute_end = absolute_start + len("private ")
        edits.append((absolute_start, absolute_end, ""))
    if not edits:
        return src, 0
    return apply_edits(src, edits), len(edits)


def apply_edits(src: str, edits: Sequence[Tuple[int, int, str]]) -> str:
    out = src
    for start, end, replacement in sorted(edits, key=lambda e: e[0], reverse=True):
        out = out[:start] + replacement + out[end:]
    return out


def render_wrapper(method: Member) -> str:
    args = ", ".join(p.name for p in method.params if p.name)
    call = f"{INDEX_FIELD}.{method.name}({args})" if args else f"{INDEX_FIELD}.{method.name}()"
    if method.return_type == "void":
        body = f" {{\n        {call};\n    }}"
    else:
        body = f" {{\n        return {call};\n    }}"
    return method.header.rstrip() + body


def method_signature_without_visibility(method: Member) -> str:
    header = method.header.strip()
    _annotations, rest = strip_leading_annotations(header)
    rest = re.sub(r"\bpublic\s+", "", rest)
    rest = re.sub(r"\bprivate\s+", "", rest)
    rest = re.sub(r"\bprotected\s+", "", rest)
    rest = re.sub(r"\bstatic\s+", "", rest)
    rest = re.sub(r"\bfinal\s+", "", rest)
    rest = re.sub(r"\bsynchronized\s+", "", rest)
    rest = re.sub(r"\s+", " ", rest).strip()
    return rest


def render_index_method(method: Member) -> str:
    signature = method_signature_without_visibility(method)
    args = ", ".join(p.name for p in method.params if p.name)
    subsystem_call = f"{method.subsystem_class}.{method.name}(owner"
    if args:
        subsystem_call += ", " + args
    subsystem_call += ")"
    if method.return_type == "void":
        body = f" {{\n        {subsystem_call};\n    }}"
    else:
        body = f" {{\n        return {subsystem_call};\n    }}"
    return f"    {signature}{body}"


def render_subsystem_method(method: Member, rewritten_body: str) -> str:
    signature = method_signature_without_visibility(method)
    name_pos = signature.find(method.name + "(")
    if name_pos < 0:
        die(f"could not render generated signature for method {method.name}")
    before_name = signature[:name_pos]
    after_name = signature[name_pos + len(method.name):]
    params_text = ", ".join(p.declaration for p in method.params)
    if params_text:
        generated_params = f"GamePanel self, {params_text}"
    else:
        generated_params = "GamePanel self"
    after_name = re.sub(r"^\s*\([^)]*\)", f"({generated_params})", after_name, count=1, flags=re.S)
    return f"    static {before_name}{method.name}{after_name} {{\n{rstrip_body(rewritten_body)}\n    }}"


def rstrip_body(body: str) -> str:
    lines = body.splitlines()
    while lines and not lines[-1].strip():
        lines.pop()
    if not lines:
        return ""
    return "\n".join(lines)


def make_file_content(package_name: str, imports: str, class_name: str, methods: Sequence[str]) -> str:
    pieces: List[str] = [GENERATED_HEADER]
    if package_name:
        pieces.append(f"package {package_name};\n\n")
    if imports:
        pieces.append(imports)
        pieces.append("\n\n")
    pieces.append(f"final class {class_name} {{\n")
    pieces.append(f"    private {class_name}() {{ }}\n\n")
    pieces.append("\n\n".join(methods))
    pieces.append("\n}\n")
    return "".join(pieces)


def make_index_content(package_name: str, imports: str, methods: Sequence[Member]) -> str:
    pieces: List[str] = [GENERATED_HEADER]
    if package_name:
        pieces.append(f"package {package_name};\n\n")
    if imports:
        pieces.append(imports)
        pieces.append("\n\n")
    pieces.append(f"final class {INDEX_CLASS} {{\n")
    pieces.append("    private final GamePanel owner;\n\n")
    pieces.append(f"    {INDEX_CLASS}(GamePanel owner) {{\n")
    pieces.append("        this.owner = owner;\n")
    pieces.append("    }\n\n")
    pieces.append("\n\n".join(render_index_method(m) for m in methods))
    pieces.append("\n}\n")
    return "".join(pieces)


def insert_index_field(src: str, clean: str, bounds: ClassBounds) -> str:
    if INDEX_FIELD in src:
        return src
    insert_at = bounds.body_start + 1
    field = (
        "\n"
        f"    private final {INDEX_CLASS} {INDEX_FIELD} = new {INDEX_CLASS}(this);\n"
    )
    return src[:insert_at] + field + src[insert_at:]


def discover_game_panel_path(explicit: Optional[str]) -> Path:
    if explicit:
        path = Path(explicit)
        if not path.exists():
            die(f"GamePanel path does not exist: {path}")
        return path

    for path in PREFERRED_GAME_PANEL_PATHS:
        if path.exists():
            return path

    matches = [p for p in ROOT.rglob("GamePanel.java") if ".git" not in p.parts]
    if not matches:
        die("could not find GamePanel.java; pass --game-panel path/to/GamePanel.java")
    matches.sort(key=lambda p: (len(p.parts), str(p)))
    return matches[0]


def choose_methods_to_move(methods: Sequence[Member], include_private: bool, max_methods: int) -> List[Member]:
    candidates: List[Member] = []
    for m in methods:
        if m.is_static:
            continue
        if m.name in {"paintComponent", "addNotify", "removeNotify"}:
            candidates.append(m)
            continue
        if not include_private and m.is_private:
            continue
        candidates.append(m)
    if max_methods > 0:
        return candidates[:max_methods]
    return candidates


def refactor_game_panel(path: Path, apply: bool, include_private: bool, max_methods: int, verbose: bool) -> RewriteReport:
    src = path.read_text(encoding="utf-8")
    clean = strip_comments_and_literals(src)
    bounds = find_game_panel_class(src, clean)
    member_ranges = collect_top_level_members(src, clean, bounds)
    methods_all = [m for r in member_ranges if (m := parse_method_member(src, clean, r)) is not None]
    if not methods_all:
        die("no GamePanel methods were identified; refusing to rewrite")

    field_names = extract_field_names(src, clean, member_ranges)
    selected = choose_methods_to_move(methods_all, include_private=include_private, max_methods=max_methods)
    if not selected:
        die("no eligible instance methods selected; use --include-private or remove --max-methods")

    for m in selected:
        label, class_name = classify_subsystem(m)
        m.subsystem_label = label
        m.subsystem_class = class_name

    generated_by_class: Dict[str, List[str]] = defaultdict(list)
    all_method_names = method_names(methods_all)

    for m in selected:
        body = rewrite_body_for_subsystem(m, field_names=field_names, game_panel_method_names=all_method_names)
        generated_by_class[m.subsystem_class].append(render_subsystem_method(m, body))

    new_src = src
    edits: List[Tuple[int, int, str]] = []
    for m in selected:
        edits.append((m.start, m.end, render_wrapper(m)))
    new_src = apply_edits(new_src, edits)

    new_clean = strip_comments_and_literals(new_src)
    new_bounds = find_game_panel_class(new_src, new_clean)
    new_src = insert_index_field(new_src, new_clean, new_bounds)

    if include_private:
        post_clean = strip_comments_and_literals(new_src)
        post_bounds = find_game_panel_class(new_src, post_clean)
        post_ranges = collect_top_level_members(new_src, post_clean, post_bounds)
        new_src, relaxed_count = remove_private_from_top_level_members(new_src, post_clean, post_bounds, post_ranges)
    else:
        relaxed_count = 0

    package_name = find_package(src)
    imports = find_import_block(src)

    out_dir = path.parent
    generated_files: Dict[Path, str] = {}
    generated_files[out_dir / f"{INDEX_CLASS}.java"] = make_index_content(package_name, imports, selected)
    for class_name, rendered_methods in sorted(generated_by_class.items()):
        generated_files[out_dir / f"{class_name}.java"] = make_file_content(package_name, imports, class_name, rendered_methods)

    report = RewriteReport(
        game_panel=rel(path),
        generated_files=[rel(p) for p in sorted(generated_files)],
        moved_methods=len(selected),
        relaxed_private_members=relaxed_count,
        source_sha256_before=sha256_text(src),
        source_sha256_after=sha256_text(new_src),
    )

    if verbose:
        print(json.dumps(dataclasses.asdict(report), indent=2))
        by_subsystem = defaultdict(list)
        for m in selected:
            by_subsystem[m.subsystem_class].append(m.name)
        for cls, names in sorted(by_subsystem.items()):
            print(f"{cls}: {', '.join(names)}")

    if apply:
        path.write_text(new_src, encoding="utf-8", newline="")
        for out_path, content in generated_files.items():
            out_path.write_text(content, encoding="utf-8", newline="")
    else:
        print("DRY RUN: no files written. Add --apply to perform the split.")
        print(json.dumps(dataclasses.asdict(report), indent=2))

    return report


def rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def run_verify(command: Sequence[str]) -> None:
    if not command:
        return
    print("Running verification:", " ".join(command))
    completed = subprocess.run(command, cwd=ROOT)
    if completed.returncode != 0:
        raise SystemExit(completed.returncode)


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Split oversized GamePanel method bodies into same-package generated subsystem classes."
    )
    parser.add_argument("--game-panel", help="Explicit path to GamePanel.java. Defaults to repo discovery.")
    parser.add_argument("--apply", action="store_true", help="Write GamePanel.java and generated subsystem files.")
    parser.add_argument("--dry-run", action="store_true", help="Inspect only. This is the default when --apply is absent.")
    parser.add_argument(
        "--include-private",
        action="store_true",
        default=True,
        help="Move private methods too and relax top-level private GamePanel members to package-private for same-package subsystem access. Default: on.",
    )
    parser.add_argument(
        "--public-only",
        action="store_true",
        help="Move only non-private methods and do not relax private members.",
    )
    parser.add_argument(
        "--max-methods",
        type=int,
        default=0,
        help="Limit moved methods for a controlled test run. 0 means all eligible methods.",
    )
    parser.add_argument(
        "--verify",
        nargs=argparse.REMAINDER,
        help="Optional verification command to run after --apply, e.g. --verify mvn -q -DskipTests package",
    )
    parser.add_argument("--verbose", action="store_true", help="Print moved methods by generated subsystem class.")
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)
    include_private = args.include_private and not args.public_only
    path = discover_game_panel_path(args.game_panel)
    if not path.name == "GamePanel.java":
        die(f"selected file is not GamePanel.java: {path}")

    report = refactor_game_panel(
        path=path,
        apply=bool(args.apply),
        include_private=include_private,
        max_methods=args.max_methods,
        verbose=args.verbose,
    )

    if args.apply and args.verify:
        run_verify(args.verify)

    if args.apply:
        print("GamePanel split complete.")
        print(json.dumps(dataclasses.asdict(report), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
