package mechanist;

import java.util.*;

/**
 * Asset integration discipline authority.
 *
 * Owns promoted runtime asset handles and the small legacy-alias bridge needed
 * for older saves. New generated objects use semantic handles; legacy names are
 * accepted only at this boundary.
 */
final class AssetIntegrationDisciplineAuthority {
    static final String VERSION = "0.9.10ak";

    static final String PUBLIC_TRASH_BIN = "public-trash-bin";
    static final String PUBLIC_WASTE_RECEPTACLE = "public-waste-receptacle";
    static final String PUBLIC_SMALL_BIN_CLUSTER = "public-small-bin-cluster";
    static final String INN_NEWSPAPER_DISPENSER = "inn-newspaper-dispenser";
    static final String DISCARDED_NEWSPRINT_SOURCE = "discarded-newsprint-source";
    static final String PUBLIC_RATION_BENCH = "public-ration-bench";
    static final String PUBLIC_PICT_SCREEN = "public-pict-screen";
    static final String CHEAP_RADIO = "cheap-radio";
    static final String PUBLIC_INFO_KIOSK = "public-info-kiosk";
    static final String PUBLIC_SERVICE_COUNTER = "public-service-counter";
    static final String MEDICAE_FRONTAGE = "medicae-frontage";
    static final String BAR_FRONTAGE = "bar-frontage";
    static final String ROAD_ALCOVE_FIXTURE = "road-alcove-fixture";
    static final String PARK_OPEN_SPACE = "park-open-space";
    static final String TAXI_BOOTH = "taxi-booth";
    static final String PARKING_LOT_MARKER = "parking-lot-marker";
    static final String ROAD_VEHICLE_STAGING_MARKER = "road-vehicle-staging-marker";
    static final String PARKED_CIVILIAN_CAR = "parked-civilian-car";
    static final String PARKED_CARGO_TRUCK = "parked-cargo-truck";
    static final String PARKED_UTILITY_BIKE = "parked-utility-bike";
    static final String PARKED_ARMORED_CAR = "parked-armored-car";
    static final String PARKED_TANK = "parked-tank";

    static final String MEDICAE_ROOM_FIXTURE = "medicae-room-fixture";
    static final String MEDICAE_CLINIC_STALL = "medicae-clinic-stall";
    static final String MEDICAE_BACKROOM_STALL = "medicae-backroom-stall";
    static final String STERILE_MEDICAE_CLEAN_BENCH = "sterile-medicae-clean-bench";
    static final String LABORATORY_ROOM_FIXTURE = "laboratory-room-fixture";
    static final String CRUDE_CHEM_BENCH_FIXTURE = "crude-chem-bench-fixture";
    static final String REAGENT_PREPARATION_BENCH_FIXTURE = "reagent-preparation-bench-fixture";
    static final String DISTILLATION_COLUMN_FIXTURE = "distillation-column-fixture";
    static final String FUME_HOOD_FIXTURE = "fume-hood-fixture";
    static final String INJECTOR_FILLING_STATION_FIXTURE = "injector-filling-station-fixture";
    static final String SCRAP_WORKBENCH_FIXTURE = "scrap-workbench-fixture";
    static final String EMM_MICRO_FORGE_FIXTURE = "emm-micro-forge-fixture";
    static final String EMM_ATMOSPHERIC_CONDENSER_FIXTURE = "emm-atmospheric-condenser-fixture";
    static final String MACHINE_MAINTENANCE_RACK_FIXTURE = "machine-maintenance-rack-fixture";
    static final String FORGE_ROOM_MACHINE = EMM_MICRO_FORGE_FIXTURE;
    static final String FACTION_BAR_INTERIOR_FIXTURE = "faction-bar-interior-fixture";
    static final String BAR_COUNTER_LONG_FIXTURE = "bar-counter-long-fixture";
    static final String BAR_BOOTH_FIXTURE = "bar-booth-fixture";
    static final String BAR_STOOL_FIXTURE = "bar-stool-fixture";
    static final String BAR_BOTTLE_SHELF_FIXTURE = "bar-bottle-shelf-fixture";
    static final String SERVICE_KEG_FIXTURE = "service-keg-fixture";
    static final String MARKET_COUNTER_FIXTURE = "market-counter-fixture";
    static final String ARBITES_COMMAND_DESK_FIXTURE = "arbites-command-desk-fixture";
    static final String ARBITES_SERGEANT_DESK_FIXTURE = "arbites-sergeant-desk-fixture";
    static final String ARBITES_COFFEE_MAKER_FIXTURE = "arbites-coffee-maker-fixture";
    static final String ARBITES_WEAPON_LOCKER_FIXTURE = "arbites-weapon-locker-fixture";
    static final String ARBITES_PERP_BENCH_FIXTURE = "arbites-perp-bench-fixture";
    static final String ARBITES_INTERROGATION_TABLE_FIXTURE = "arbites-interrogation-table-fixture";
    static final String ARBITES_HOLDING_CELL_FIXTURE = "arbites-holding-cell-fixture";
    static final String ARBITES_PRECINCT_DOOR_FIXTURE = "arbites-precinct-door-fixture";
    static final String ARBITES_PRECINCT_SIGN_FIXTURE = "arbites-precinct-sign-fixture";
    static final String ARBITES_ALARM_PANEL_FIXTURE = "arbites-alarm-panel-fixture";
    static final String ARBITES_EVIDENCE_LOCKER_FIXTURE = "arbites-evidence-locker-fixture";
    static final String NOBLE_WALL_PANEL_FIXTURE = "noble-wall-panel-fixture";
    static final String NOBLE_GATE_FIXTURE = "noble-gate-fixture";
    static final String NOBLE_CORNER_TOWER_FIXTURE = "noble-corner-tower-fixture";
    static final String NOBLE_GILDED_SENTRY_FIXTURE = "noble-gilded-sentry-fixture";
    static final String NOBLE_SHIELD_RELAY_FIXTURE = "noble-shield-relay-fixture";
    static final String NOBLE_VOID_SHIELD_DOME_FIXTURE = "noble-void-shield-dome-fixture";
    static final String NOBLE_LASER_PYLON_FIXTURE = "noble-laser-pylon-fixture";
    static final String NOBLE_ENERGY_FENCE_FIXTURE = "noble-energy-fence-fixture";
    static final String NOBLE_SECURITY_PANEL_FIXTURE = "noble-security-panel-fixture";
    static final String PDF_WALL_PANEL_FIXTURE = "pdf-wall-panel-fixture";
    static final String PDF_WALL_CORNER_FIXTURE = "pdf-wall-corner-fixture";
    static final String PDF_GATE_FIXTURE = "pdf-gate-fixture";
    static final String PDF_WALL_DAMAGED_FIXTURE = "pdf-wall-damaged-fixture";
    static final String PDF_TURRET_MK1_FIXTURE = "pdf-turret-mk1-fixture";
    static final String PDF_TURRET_MK2_FIXTURE = "pdf-turret-mk2-fixture";
    static final String PDF_TURRET_MK3_FIXTURE = "pdf-turret-mk3-fixture";
    static final String PDF_SANDBAG_BARRICADE_FIXTURE = "pdf-sandbag-barricade-fixture";
    static final String PDF_SANDBAG_CORNER_FIXTURE = "pdf-sandbag-corner-fixture";
    static final String GUARD_BARRACKS_ANCHOR_FIXTURE = "guard-barracks-anchor-fixture";
    static final String GUARD_WATCH_POST_FIXTURE = "guard-watch-post-fixture";
    static final String GUARD_SUPPLY_POST_FIXTURE = "guard-supply-post-fixture";
    static final String ALGAE_TANK_FIXTURE = "algae-tank-fixture";
    static final String HYDROPONICS_BED_FIXTURE = "hydroponics-bed-fixture";
    static final String ANIMAL_PEN_FIXTURE = "animal-pen-fixture";
    static final String CLONING_VAT_FIXTURE = "cloning-vat-fixture";
    static final String FUNGAL_GROW_TRAY_FIXTURE = "fungal-grow-tray-fixture";
    static final String REFRIGERATED_FOOD_STORE_FIXTURE = "refrigerated-food-store-fixture";
    static final String NUTRIENT_VAT_FIXTURE = "nutrient-vat-fixture";
    static final String HAB_COT_FIXTURE = "hab-cot-fixture";
    static final String GUARD_COT_FIXTURE = "guard-cot-fixture";
    static final String WORN_BED_FIXTURE = "worn-bed-fixture";
    static final String NOBLE_BED_FIXTURE = "noble-bed-fixture";
    static final String BUNK_BED_FIXTURE = "bunk-bed-fixture";
    static final String DOMESTIC_WATER_STORAGE_FIXTURE = "domestic-water-storage-fixture";
    static final String DOMESTIC_REFRIGERATOR_FIXTURE = "domestic-refrigerator-fixture";
    static final String DOMESTIC_SINK_FIXTURE = "domestic-sink-fixture";
    static final String DOMESTIC_STOVE_FIXTURE = "domestic-stove-fixture";
    static final String DOMESTIC_PREP_COUNTER_FIXTURE = "domestic-prep-counter-fixture";
    static final String DOMESTIC_STORAGE_CABINET_FIXTURE = "domestic-storage-cabinet-fixture";
    static final String DOMESTIC_PLANK_TABLE_FIXTURE = "domestic-plank-table-fixture";
    static final String DOMESTIC_ROUND_TABLE_FIXTURE = "domestic-round-table-fixture";
    static final String DOMESTIC_MESS_TABLE_FIXTURE = "domestic-mess-table-fixture";
    static final String DOMESTIC_ORNATE_TABLE_FIXTURE = "domestic-ornate-table-fixture";
    static final String CIVIC_INTERIOR_SERVICE_FIXTURE = "civic-interior-service-fixture";

    private static final Map<String, String> LEGACY_TO_CANONICAL = new LinkedHashMap<>();
    private static final Map<String, String> CANONICAL_TO_SEMANTIC = new LinkedHashMap<>();
    private static final Set<String> PROMOTED = new LinkedHashSet<>();

    static {
        alias("public-trash-bin-placeholder", PUBLIC_TRASH_BIN);
        alias("public-waste-receptacle-placeholder", PUBLIC_WASTE_RECEPTACLE);
        alias("public-receptacle-placeholder", PUBLIC_WASTE_RECEPTACLE);
        alias("public-small-bin-cluster-placeholder", PUBLIC_SMALL_BIN_CLUSTER);
        alias("small-bin-cluster-placeholder", PUBLIC_SMALL_BIN_CLUSTER);
        alias("newspaper-vending", INN_NEWSPAPER_DISPENSER);
        alias("inn-newspaper-vending", INN_NEWSPAPER_DISPENSER);
        alias("old-newspaper", DISCARDED_NEWSPRINT_SOURCE);
        alias("old-newspaper-source", DISCARDED_NEWSPRINT_SOURCE);
        alias("public-ration-bench-placeholder", PUBLIC_RATION_BENCH);
        alias("public-pict-screen-placeholder", PUBLIC_PICT_SCREEN);
        alias("cheap-radio-placeholder", CHEAP_RADIO);
        alias("public-info-kiosk-placeholder", PUBLIC_INFO_KIOSK);
        alias("public-service-counter-placeholder", PUBLIC_SERVICE_COUNTER);
        alias("medicae-frontage-placeholder", MEDICAE_FRONTAGE);
        alias("bar-frontage-placeholder", BAR_FRONTAGE);
        alias("park-open-space-placeholder", PARK_OPEN_SPACE);
        alias("taxi-booth-placeholder", TAXI_BOOTH);
        alias("taxi-toll-booth-placeholder", TAXI_BOOTH);
        alias("parking-lot-placeholder", PARKING_LOT_MARKER);
        alias("road-vehicle-staging-marker-placeholder", ROAD_VEHICLE_STAGING_MARKER);
        alias("vehicle-staging-marker", ROAD_VEHICLE_STAGING_MARKER);
        alias("vehicle-car-placeholder", PARKED_CIVILIAN_CAR);
        alias("vehicle-truck-placeholder", PARKED_CARGO_TRUCK);
        alias("vehicle-bike-placeholder", PARKED_UTILITY_BIKE);
        alias("vehicle-armored-car-placeholder", PARKED_ARMORED_CAR);
        alias("vehicle-tank-placeholder", PARKED_TANK);
        alias("medicae-room-fixture-placeholder", MEDICAE_ROOM_FIXTURE);
        alias("clinic-stall", MEDICAE_CLINIC_STALL);
        alias("clinic-stall-placeholder", MEDICAE_CLINIC_STALL);
        alias("medicae-clinic-stall-placeholder", MEDICAE_CLINIC_STALL);
        alias("backroom-medicae-stall", MEDICAE_BACKROOM_STALL);
        alias("backroom-medicae-stall-placeholder", MEDICAE_BACKROOM_STALL);
        alias("sterile-medicae-clean-bench-placeholder", STERILE_MEDICAE_CLEAN_BENCH);
        alias("sterile-medicae-bench", STERILE_MEDICAE_CLEAN_BENCH);
        alias("laboratory-room-fixture-placeholder", LABORATORY_ROOM_FIXTURE);
        alias("micro-lab-fixture", LABORATORY_ROOM_FIXTURE);
        alias("micro-laboratory-fixture", LABORATORY_ROOM_FIXTURE);
        alias("crude-chem-bench", CRUDE_CHEM_BENCH_FIXTURE);
        alias("crude-chem-bench-placeholder", CRUDE_CHEM_BENCH_FIXTURE);
        alias("chem-bench-fixture", CRUDE_CHEM_BENCH_FIXTURE);
        alias("reagent-preparation-bench", REAGENT_PREPARATION_BENCH_FIXTURE);
        alias("reagent-preparation-bench-placeholder", REAGENT_PREPARATION_BENCH_FIXTURE);
        alias("reagent-bench-fixture", REAGENT_PREPARATION_BENCH_FIXTURE);
        alias("distillation-column", DISTILLATION_COLUMN_FIXTURE);
        alias("distillation-column-placeholder", DISTILLATION_COLUMN_FIXTURE);
        alias("distillation-column-fixture-placeholder", DISTILLATION_COLUMN_FIXTURE);
        alias("fume-hood", FUME_HOOD_FIXTURE);
        alias("fume-hood-placeholder", FUME_HOOD_FIXTURE);
        alias("fume-hood-fixture-placeholder", FUME_HOOD_FIXTURE);
        alias("injector-filling-station", INJECTOR_FILLING_STATION_FIXTURE);
        alias("injector-filling-station-placeholder", INJECTOR_FILLING_STATION_FIXTURE);
        alias("injector-station-fixture", INJECTOR_FILLING_STATION_FIXTURE);
        alias("forge-room-machine", EMM_MICRO_FORGE_FIXTURE);
        alias("forge-room-machine-placeholder", EMM_MICRO_FORGE_FIXTURE);
        alias("micro-forge-fixture", EMM_MICRO_FORGE_FIXTURE);
        alias("emm-micro-forge", EMM_MICRO_FORGE_FIXTURE);
        alias("emm-micro-forge-placeholder", EMM_MICRO_FORGE_FIXTURE);
        alias("scrap-workbench", SCRAP_WORKBENCH_FIXTURE);
        alias("scrap-workbench-placeholder", SCRAP_WORKBENCH_FIXTURE);
        alias("workbench-fixture", SCRAP_WORKBENCH_FIXTURE);
        alias("atmospheric-condenser-fixture", EMM_ATMOSPHERIC_CONDENSER_FIXTURE);
        alias("emm-atmospheric-condenser", EMM_ATMOSPHERIC_CONDENSER_FIXTURE);
        alias("emm-atmospheric-condenser-placeholder", EMM_ATMOSPHERIC_CONDENSER_FIXTURE);
        alias("machine-maintenance-rack", MACHINE_MAINTENANCE_RACK_FIXTURE);
        alias("machine-maintenance-rack-placeholder", MACHINE_MAINTENANCE_RACK_FIXTURE);
        alias("maintenance-rack-fixture", MACHINE_MAINTENANCE_RACK_FIXTURE);
        alias("faction-bar-interior-fixture-placeholder", FACTION_BAR_INTERIOR_FIXTURE);
        alias("bar-counter-long", BAR_COUNTER_LONG_FIXTURE);
        alias("bar-counter-long-placeholder", BAR_COUNTER_LONG_FIXTURE);
        alias("bar-counter-long-fixture-placeholder", BAR_COUNTER_LONG_FIXTURE);
        alias("bar-counter", BAR_COUNTER_LONG_FIXTURE);
        alias("bar-booth", BAR_BOOTH_FIXTURE);
        alias("bar-booth-placeholder", BAR_BOOTH_FIXTURE);
        alias("bar-booth-fixture-placeholder", BAR_BOOTH_FIXTURE);
        alias("bar-stool", BAR_STOOL_FIXTURE);
        alias("bar-stool-placeholder", BAR_STOOL_FIXTURE);
        alias("bar-stool-fixture-placeholder", BAR_STOOL_FIXTURE);
        alias("bar-bottle-shelf", BAR_BOTTLE_SHELF_FIXTURE);
        alias("bar-bottle-shelf-placeholder", BAR_BOTTLE_SHELF_FIXTURE);
        alias("bar-bottle-shelf-fixture-placeholder", BAR_BOTTLE_SHELF_FIXTURE);
        alias("service-keg", SERVICE_KEG_FIXTURE);
        alias("service-keg-placeholder", SERVICE_KEG_FIXTURE);
        alias("service-keg-fixture-placeholder", SERVICE_KEG_FIXTURE);
        alias("market-counter", MARKET_COUNTER_FIXTURE);
        alias("market-counter-placeholder", MARKET_COUNTER_FIXTURE);
        alias("market-counter-fixture-placeholder", MARKET_COUNTER_FIXTURE);
        alias("shop-counter-fixture", MARKET_COUNTER_FIXTURE);
        alias("arbites-command-desk", ARBITES_COMMAND_DESK_FIXTURE);
        alias("arbites-command-desk-placeholder", ARBITES_COMMAND_DESK_FIXTURE);
        alias("command-desk-fixture", ARBITES_COMMAND_DESK_FIXTURE);
        alias("arbites-sergeant-desk", ARBITES_SERGEANT_DESK_FIXTURE);
        alias("arbites-sergeant-desk-placeholder", ARBITES_SERGEANT_DESK_FIXTURE);
        alias("sergeant-desk-fixture", ARBITES_SERGEANT_DESK_FIXTURE);
        alias("arbites-coffee-maker", ARBITES_COFFEE_MAKER_FIXTURE);
        alias("arbites-coffee-maker-placeholder", ARBITES_COFFEE_MAKER_FIXTURE);
        alias("precinct-coffee-maker-fixture", ARBITES_COFFEE_MAKER_FIXTURE);
        alias("arbites-weapon-locker", ARBITES_WEAPON_LOCKER_FIXTURE);
        alias("arbites-weapon-locker-placeholder", ARBITES_WEAPON_LOCKER_FIXTURE);
        alias("precinct-weapon-locker-fixture", ARBITES_WEAPON_LOCKER_FIXTURE);
        alias("arbites-perp-bench", ARBITES_PERP_BENCH_FIXTURE);
        alias("arbites-perp-bench-placeholder", ARBITES_PERP_BENCH_FIXTURE);
        alias("perp-bench-fixture", ARBITES_PERP_BENCH_FIXTURE);
        alias("arbites-interrogation-table", ARBITES_INTERROGATION_TABLE_FIXTURE);
        alias("arbites-interrogation-table-placeholder", ARBITES_INTERROGATION_TABLE_FIXTURE);
        alias("interrogation-table-fixture", ARBITES_INTERROGATION_TABLE_FIXTURE);
        alias("arbites-holding-cell", ARBITES_HOLDING_CELL_FIXTURE);
        alias("arbites-holding-cell-placeholder", ARBITES_HOLDING_CELL_FIXTURE);
        alias("holding-cell-fixture", ARBITES_HOLDING_CELL_FIXTURE);
        alias("arbites-precinct-door", ARBITES_PRECINCT_DOOR_FIXTURE);
        alias("arbites-precinct-door-placeholder", ARBITES_PRECINCT_DOOR_FIXTURE);
        alias("precinct-door-fixture", ARBITES_PRECINCT_DOOR_FIXTURE);
        alias("arbites-precinct-sign", ARBITES_PRECINCT_SIGN_FIXTURE);
        alias("arbites-precinct-sign-placeholder", ARBITES_PRECINCT_SIGN_FIXTURE);
        alias("precinct-sign-fixture", ARBITES_PRECINCT_SIGN_FIXTURE);
        alias("arbites-alarm-panel", ARBITES_ALARM_PANEL_FIXTURE);
        alias("arbites-alarm-panel-placeholder", ARBITES_ALARM_PANEL_FIXTURE);
        alias("precinct-alarm-panel-fixture", ARBITES_ALARM_PANEL_FIXTURE);
        alias("arbites-evidence-locker", ARBITES_EVIDENCE_LOCKER_FIXTURE);
        alias("arbites-evidence-locker-placeholder", ARBITES_EVIDENCE_LOCKER_FIXTURE);
        alias("evidence-locker-fixture", ARBITES_EVIDENCE_LOCKER_FIXTURE);
        alias("noble-wall-panel", NOBLE_WALL_PANEL_FIXTURE);
        alias("noble-wall-panel-placeholder", NOBLE_WALL_PANEL_FIXTURE);
        alias("noble-house-wall-panel", NOBLE_WALL_PANEL_FIXTURE);
        alias("noble-gate", NOBLE_GATE_FIXTURE);
        alias("noble-gate-placeholder", NOBLE_GATE_FIXTURE);
        alias("gilded-noble-gate", NOBLE_GATE_FIXTURE);
        alias("noble-corner-tower", NOBLE_CORNER_TOWER_FIXTURE);
        alias("noble-corner-tower-placeholder", NOBLE_CORNER_TOWER_FIXTURE);
        alias("gilded-corner-tower", NOBLE_CORNER_TOWER_FIXTURE);
        alias("noble-gilded-sentry", NOBLE_GILDED_SENTRY_FIXTURE);
        alias("noble-gilded-sentry-placeholder", NOBLE_GILDED_SENTRY_FIXTURE);
        alias("gilded-sentry-turret-fixture", NOBLE_GILDED_SENTRY_FIXTURE);
        alias("noble-turret", NOBLE_GILDED_SENTRY_FIXTURE);
        alias("noble-shield-relay", NOBLE_SHIELD_RELAY_FIXTURE);
        alias("noble-shield-relay-placeholder", NOBLE_SHIELD_RELAY_FIXTURE);
        alias("gilded-shield-relay", NOBLE_SHIELD_RELAY_FIXTURE);
        alias("noble-void-shield-dome", NOBLE_VOID_SHIELD_DOME_FIXTURE);
        alias("noble-void-shield-dome-placeholder", NOBLE_VOID_SHIELD_DOME_FIXTURE);
        alias("void-shield-dome-fixture", NOBLE_VOID_SHIELD_DOME_FIXTURE);
        alias("noble-laser-pylon", NOBLE_LASER_PYLON_FIXTURE);
        alias("noble-laser-pylon-placeholder", NOBLE_LASER_PYLON_FIXTURE);
        alias("gilded-laser-pylon", NOBLE_LASER_PYLON_FIXTURE);
        alias("noble-energy-fence", NOBLE_ENERGY_FENCE_FIXTURE);
        alias("noble-energy-fence-placeholder", NOBLE_ENERGY_FENCE_FIXTURE);
        alias("gilded-energy-fence", NOBLE_ENERGY_FENCE_FIXTURE);
        alias("noble-security-panel", NOBLE_SECURITY_PANEL_FIXTURE);
        alias("noble-security-panel-placeholder", NOBLE_SECURITY_PANEL_FIXTURE);
        alias("estate-security-panel-fixture", NOBLE_SECURITY_PANEL_FIXTURE);
        alias("pdf-wall-panel", PDF_WALL_PANEL_FIXTURE);
        alias("pdf-wall-panel-placeholder", PDF_WALL_PANEL_FIXTURE);
        alias("guard-wall-panel", PDF_WALL_PANEL_FIXTURE);
        alias("astra-militarum-wall-panel", PDF_WALL_PANEL_FIXTURE);
        alias("pdf-wall-corner", PDF_WALL_CORNER_FIXTURE);
        alias("pdf-wall-corner-placeholder", PDF_WALL_CORNER_FIXTURE);
        alias("guard-wall-corner", PDF_WALL_CORNER_FIXTURE);
        alias("pdf-gate", PDF_GATE_FIXTURE);
        alias("pdf-gate-placeholder", PDF_GATE_FIXTURE);
        alias("guard-checkpoint-gate", PDF_GATE_FIXTURE);
        alias("astra-militarum-gate", PDF_GATE_FIXTURE);
        alias("pdf-wall-damaged", PDF_WALL_DAMAGED_FIXTURE);
        alias("pdf-wall-damaged-placeholder", PDF_WALL_DAMAGED_FIXTURE);
        alias("damaged-guard-wall", PDF_WALL_DAMAGED_FIXTURE);
        alias("pdf-turret-mk1", PDF_TURRET_MK1_FIXTURE);
        alias("pdf-turret-mk1-placeholder", PDF_TURRET_MK1_FIXTURE);
        alias("guard-turret-mk1", PDF_TURRET_MK1_FIXTURE);
        alias("pdf-turret-mk2", PDF_TURRET_MK2_FIXTURE);
        alias("pdf-turret-mk2-placeholder", PDF_TURRET_MK2_FIXTURE);
        alias("guard-turret-mk2", PDF_TURRET_MK2_FIXTURE);
        alias("pdf-turret-mk3", PDF_TURRET_MK3_FIXTURE);
        alias("pdf-turret-mk3-placeholder", PDF_TURRET_MK3_FIXTURE);
        alias("guard-turret-mk3", PDF_TURRET_MK3_FIXTURE);
        alias("sandbag-barricade", PDF_SANDBAG_BARRICADE_FIXTURE);
        alias("sandbag-barricade-placeholder", PDF_SANDBAG_BARRICADE_FIXTURE);
        alias("pdf-sandbag-barricade", PDF_SANDBAG_BARRICADE_FIXTURE);
        alias("sandbag-corner", PDF_SANDBAG_CORNER_FIXTURE);
        alias("sandbag-corner-placeholder", PDF_SANDBAG_CORNER_FIXTURE);
        alias("pdf-sandbag-corner", PDF_SANDBAG_CORNER_FIXTURE);
        alias("guard-barracks-anchor", GUARD_BARRACKS_ANCHOR_FIXTURE);
        alias("guard-barracks-anchor-placeholder", GUARD_BARRACKS_ANCHOR_FIXTURE);
        alias("guard-watch-post", GUARD_WATCH_POST_FIXTURE);
        alias("guard-watch-post-placeholder", GUARD_WATCH_POST_FIXTURE);
        alias("guard-supply-post", GUARD_SUPPLY_POST_FIXTURE);
        alias("guard-supply-post-placeholder", GUARD_SUPPLY_POST_FIXTURE);
        alias("algae-tank", ALGAE_TANK_FIXTURE);
        alias("algae-tank-placeholder", ALGAE_TANK_FIXTURE);
        alias("algae-culture-tank", ALGAE_TANK_FIXTURE);
        alias("hydroponics-bed", HYDROPONICS_BED_FIXTURE);
        alias("hydroponics-bed-placeholder", HYDROPONICS_BED_FIXTURE);
        alias("hydroponic-bed-fixture", HYDROPONICS_BED_FIXTURE);
        alias("animal-pen", ANIMAL_PEN_FIXTURE);
        alias("animal-pen-placeholder", ANIMAL_PEN_FIXTURE);
        alias("livestock-pen-fixture", ANIMAL_PEN_FIXTURE);
        alias("cloning-vat", CLONING_VAT_FIXTURE);
        alias("cloning-vat-placeholder", CLONING_VAT_FIXTURE);
        alias("bio-growth-vat", CLONING_VAT_FIXTURE);
        alias("fungal-grow-tray", FUNGAL_GROW_TRAY_FIXTURE);
        alias("fungal-grow-tray-placeholder", FUNGAL_GROW_TRAY_FIXTURE);
        alias("fungal-grow-tray-bank", FUNGAL_GROW_TRAY_FIXTURE);
        alias("fungus-grow-tray", FUNGAL_GROW_TRAY_FIXTURE);
        alias("refrigerated-food-store", REFRIGERATED_FOOD_STORE_FIXTURE);
        alias("refrigerated-food-store-placeholder", REFRIGERATED_FOOD_STORE_FIXTURE);
        alias("refrigerator-fixture", REFRIGERATED_FOOD_STORE_FIXTURE);
        alias("food-refrigerator", REFRIGERATED_FOOD_STORE_FIXTURE);
        alias("nutrient-vat", NUTRIENT_VAT_FIXTURE);
        alias("nutrient-vat-placeholder", NUTRIENT_VAT_FIXTURE);
        alias("nutrient-slurry-vat", NUTRIENT_VAT_FIXTURE);
        alias("sleeping-cot", HAB_COT_FIXTURE);
        alias("sleeping-cot-placeholder", HAB_COT_FIXTURE);
        alias("hab-cot", HAB_COT_FIXTURE);
        alias("guard-cot", GUARD_COT_FIXTURE);
        alias("military-cot", GUARD_COT_FIXTURE);
        alias("worn-bed", WORN_BED_FIXTURE);
        alias("underhive-bed", WORN_BED_FIXTURE);
        alias("noble-bed", NOBLE_BED_FIXTURE);
        alias("estate-bed", NOBLE_BED_FIXTURE);
        alias("bunk-bed", BUNK_BED_FIXTURE);
        alias("dormitory-bunk", BUNK_BED_FIXTURE);
        alias("water-barrel", DOMESTIC_WATER_STORAGE_FIXTURE);
        alias("domestic-water-barrel", DOMESTIC_WATER_STORAGE_FIXTURE);
        alias("water-dispenser", DOMESTIC_WATER_STORAGE_FIXTURE);
        alias("domestic-fridge", DOMESTIC_REFRIGERATOR_FIXTURE);
        alias("domestic-refrigerator", DOMESTIC_REFRIGERATOR_FIXTURE);
        alias("domestic-cold-box", DOMESTIC_REFRIGERATOR_FIXTURE);
        alias("domestic-sink", DOMESTIC_SINK_FIXTURE);
        alias("sink-counter", DOMESTIC_SINK_FIXTURE);
        alias("domestic-stove", DOMESTIC_STOVE_FIXTURE);
        alias("stove-counter", DOMESTIC_STOVE_FIXTURE);
        alias("domestic-prep-counter", DOMESTIC_PREP_COUNTER_FIXTURE);
        alias("domestic-cabinet", DOMESTIC_STORAGE_CABINET_FIXTURE);
        alias("dresser-storage", DOMESTIC_STORAGE_CABINET_FIXTURE);
        alias("plank-table", DOMESTIC_PLANK_TABLE_FIXTURE);
        alias("round-table", DOMESTIC_ROUND_TABLE_FIXTURE);
        alias("mess-table", DOMESTIC_MESS_TABLE_FIXTURE);
        alias("ornate-dining-table", DOMESTIC_ORNATE_TABLE_FIXTURE);
        alias("civic-interior-service-fixture-placeholder", CIVIC_INTERIOR_SERVICE_FIXTURE);

        semantic(PUBLIC_TRASH_BIN, "feature_public_trash_bin");
        semantic(PUBLIC_WASTE_RECEPTACLE, "feature_public_receptacle");
        semantic(PUBLIC_SMALL_BIN_CLUSTER, "feature_public_small_bin_cluster");
        semantic(INN_NEWSPAPER_DISPENSER, "feature_newspaper_vending");
        semantic(DISCARDED_NEWSPRINT_SOURCE, "feature_old_newspaper_source");
        semantic(PUBLIC_RATION_BENCH, "feature_public_ration_bench");
        semantic(PUBLIC_PICT_SCREEN, "feature_broadcast_pict_screen");
        semantic(CHEAP_RADIO, "feature_broadcast_radio");
        semantic(PUBLIC_INFO_KIOSK, "feature_public_info_column");
        semantic(PUBLIC_SERVICE_COUNTER, "feature_public_service_counter");
        semantic(MEDICAE_FRONTAGE, "feature_public_notice_wall");
        semantic(BAR_FRONTAGE, "feature_faction_rep_bar_counter");
        semantic(ROAD_ALCOVE_FIXTURE, "feature_public_service_counter");
        semantic(PARK_OPEN_SPACE, "feature_park_planter");
        semantic(TAXI_BOOTH, "feature_public_info_column");
        semantic(PARKING_LOT_MARKER, "tile_road_intersection");
        semantic(ROAD_VEHICLE_STAGING_MARKER, "entity_car");
        semantic(PARKED_CIVILIAN_CAR, "entity_car");
        semantic(PARKED_CARGO_TRUCK, "entity_truck");
        semantic(PARKED_UTILITY_BIKE, "entity_bike");
        semantic(PARKED_ARMORED_CAR, "entity_armored_car");
        semantic(PARKED_TANK, "entity_tank");
        semantic(MEDICAE_ROOM_FIXTURE, "build_backroom_medicae_stall");
        semantic(MEDICAE_CLINIC_STALL, "build_clinic_stall");
        semantic(MEDICAE_BACKROOM_STALL, "build_backroom_medicae_stall");
        semantic(STERILE_MEDICAE_CLEAN_BENCH, "build_sterile_medicae_clean_bench");
        semantic(LABORATORY_ROOM_FIXTURE, "build_emm_micro_lab");
        semantic(CRUDE_CHEM_BENCH_FIXTURE, "build_crude_chem_bench");
        semantic(REAGENT_PREPARATION_BENCH_FIXTURE, "build_reagent_preparation_bench");
        semantic(DISTILLATION_COLUMN_FIXTURE, "build_distillation_column");
        semantic(FUME_HOOD_FIXTURE, "build_fume_hood");
        semantic(INJECTOR_FILLING_STATION_FIXTURE, "build_injector_filling_station");
        semantic(SCRAP_WORKBENCH_FIXTURE, "build_scrap_workbench");
        semantic(EMM_MICRO_FORGE_FIXTURE, "build_emm_micro_forge");
        semantic(EMM_ATMOSPHERIC_CONDENSER_FIXTURE, "build_emm_atmospheric_condenser");
        semantic(MACHINE_MAINTENANCE_RACK_FIXTURE, "build_business_addon_fixture");
        semantic(FACTION_BAR_INTERIOR_FIXTURE, "feature_faction_rep_bar_counter");
        semantic(BAR_COUNTER_LONG_FIXTURE, "feature_bar_counter_long");
        semantic(BAR_BOOTH_FIXTURE, "feature_bar_booth");
        semantic(BAR_STOOL_FIXTURE, "feature_bar_stool");
        semantic(BAR_BOTTLE_SHELF_FIXTURE, "feature_bar_bottle_shelf");
        semantic(SERVICE_KEG_FIXTURE, "feature_service_keg");
        semantic(MARKET_COUNTER_FIXTURE, "build_licensed_shop_counter");
        semantic(ARBITES_COMMAND_DESK_FIXTURE, "feature_arbites_command_desk");
        semantic(ARBITES_SERGEANT_DESK_FIXTURE, "feature_arbites_sergeant_desk");
        semantic(ARBITES_COFFEE_MAKER_FIXTURE, "feature_arbites_coffee_maker");
        semantic(ARBITES_WEAPON_LOCKER_FIXTURE, "feature_arbites_weapon_locker");
        semantic(ARBITES_PERP_BENCH_FIXTURE, "feature_arbites_perp_bench");
        semantic(ARBITES_INTERROGATION_TABLE_FIXTURE, "feature_arbites_interrogation_table");
        semantic(ARBITES_HOLDING_CELL_FIXTURE, "feature_arbites_holding_cell");
        semantic(ARBITES_PRECINCT_DOOR_FIXTURE, "feature_arbites_precinct_door");
        semantic(ARBITES_PRECINCT_SIGN_FIXTURE, "feature_arbites_precinct_sign");
        semantic(ARBITES_ALARM_PANEL_FIXTURE, "feature_arbites_alarm_panel");
        semantic(ARBITES_EVIDENCE_LOCKER_FIXTURE, "feature_arbites_evidence_locker");
        semantic(NOBLE_WALL_PANEL_FIXTURE, "build_noble_wall_panel");
        semantic(NOBLE_GATE_FIXTURE, "build_noble_gate");
        semantic(NOBLE_CORNER_TOWER_FIXTURE, "build_noble_corner_tower");
        semantic(NOBLE_GILDED_SENTRY_FIXTURE, "build_noble_turret");
        semantic(NOBLE_SHIELD_RELAY_FIXTURE, "build_noble_shield_relay");
        semantic(NOBLE_VOID_SHIELD_DOME_FIXTURE, "build_noble_void_shield_dome");
        semantic(NOBLE_LASER_PYLON_FIXTURE, "build_noble_laser_pylon");
        semantic(NOBLE_ENERGY_FENCE_FIXTURE, "build_noble_energy_fence");
        semantic(NOBLE_SECURITY_PANEL_FIXTURE, "feature_noble_security_panel");
        semantic(PDF_WALL_PANEL_FIXTURE, "build_pdf_wall_panel");
        semantic(PDF_WALL_CORNER_FIXTURE, "build_pdf_wall_corner");
        semantic(PDF_GATE_FIXTURE, "build_pdf_gate");
        semantic(PDF_WALL_DAMAGED_FIXTURE, "build_pdf_wall_damaged");
        semantic(PDF_TURRET_MK1_FIXTURE, "build_pdf_turret_mk1");
        semantic(PDF_TURRET_MK2_FIXTURE, "build_pdf_turret_mk2");
        semantic(PDF_TURRET_MK3_FIXTURE, "build_pdf_turret_mk3");
        semantic(PDF_SANDBAG_BARRICADE_FIXTURE, "build_sandbag_barricade");
        semantic(PDF_SANDBAG_CORNER_FIXTURE, "build_sandbag_corner");
        semantic(GUARD_BARRACKS_ANCHOR_FIXTURE, "build_pdf_wall_panel");
        semantic(GUARD_WATCH_POST_FIXTURE, "feature_alarm_sensor_post");
        semantic(GUARD_SUPPLY_POST_FIXTURE, "build_sandbag_barricade");
        semantic(ALGAE_TANK_FIXTURE, "feature_algae_tank");
        semantic(HYDROPONICS_BED_FIXTURE, "feature_hydroponics_bed");
        semantic(ANIMAL_PEN_FIXTURE, "feature_animal_pen");
        semantic(CLONING_VAT_FIXTURE, "feature_cloning_vat");
        semantic(FUNGAL_GROW_TRAY_FIXTURE, "feature_hydroponics_bed");
        semantic(REFRIGERATED_FOOD_STORE_FIXTURE, "feature_refrigerator");
        semantic(NUTRIENT_VAT_FIXTURE, "feature_algae_tank");
        semantic(HAB_COT_FIXTURE, "feature_hab_cot_plain");
        semantic(GUARD_COT_FIXTURE, "feature_hab_cot_guard");
        semantic(WORN_BED_FIXTURE, "feature_hab_cot_worn");
        semantic(NOBLE_BED_FIXTURE, "feature_hab_bed_noble");
        semantic(BUNK_BED_FIXTURE, "feature_hab_bunk_bed");
        semantic(DOMESTIC_WATER_STORAGE_FIXTURE, "feature_domestic_water_dispenser");
        semantic(DOMESTIC_REFRIGERATOR_FIXTURE, "feature_domestic_refrigerator_white");
        semantic(DOMESTIC_SINK_FIXTURE, "feature_domestic_sink_counter");
        semantic(DOMESTIC_STOVE_FIXTURE, "feature_domestic_stove_counter");
        semantic(DOMESTIC_PREP_COUNTER_FIXTURE, "feature_domestic_prep_counter");
        semantic(DOMESTIC_STORAGE_CABINET_FIXTURE, "feature_domestic_cabinet_counter");
        semantic(DOMESTIC_PLANK_TABLE_FIXTURE, "feature_domestic_plank_table");
        semantic(DOMESTIC_ROUND_TABLE_FIXTURE, "feature_domestic_round_table");
        semantic(DOMESTIC_MESS_TABLE_FIXTURE, "feature_domestic_square_mess_table");
        semantic(DOMESTIC_ORNATE_TABLE_FIXTURE, "feature_domestic_ornate_dining_table");
        semantic(CIVIC_INTERIOR_SERVICE_FIXTURE, "feature_public_service_counter");
    }

    private AssetIntegrationDisciplineAuthority() {}

    private static void alias(String legacy, String canonical) { LEGACY_TO_CANONICAL.put(legacy, canonical); }
    private static void semantic(String canonical, String semanticKey) { PROMOTED.add(canonical); CANONICAL_TO_SEMANTIC.put(canonical, semanticKey); }

    static String canonicalType(String type) { if (type == null) return null; return LEGACY_TO_CANONICAL.getOrDefault(type, type); }
    static boolean isPromotedType(String type) { String canonical = canonicalType(type); return canonical != null && PROMOTED.contains(canonical); }
    static String semanticKeyForType(String type) { String canonical = canonicalType(type); return canonical == null ? null : CANONICAL_TO_SEMANTIC.get(canonical); }

    static String semanticKeyForMapObject(MapObjectState obj) {
        if (obj == null || obj.type == null) return null;
        String type = canonicalType(obj.type);
        String direct = semanticKeyForType(type);
        if (direct != null) return direct;
        String medicae = MedicaeFixtureAuthority.artKeyForType(type);
        if (medicae != null) return medicae;
        String labChemical = LabChemicalFixtureAuthority.artKeyForType(type);
        if (labChemical != null) return labChemical;
        String industrialForge = IndustrialForgeFixtureAuthority.artKeyForType(type);
        if (industrialForge != null) return industrialForge;
        String barMarketSocial = BarMarketSocialFixtureAuthority.artKeyForType(type);
        if (barMarketSocial != null) return barMarketSocial;
        String arbitesPrecinct = ArbitesPrecinctFixtureAuthority.artKeyForType(type);
        if (arbitesPrecinct != null) return arbitesPrecinct;
        String nobleSecurity = NobleEstateSecurityFixtureAuthority.artKeyForType(type);
        if (nobleSecurity != null) return nobleSecurity;
        String guardPdfDefense = GuardPdfDefenseFixtureAuthority.artKeyForType(type);
        if (guardPdfDefense != null) return guardPdfDefense;
        String roadTransit = RoadTransitFixtureAuthority.artKeyForType(type);
        if (roadTransit != null) return roadTransit;
        String foodBio = FoodBioProductionFixtureAuthority.artKeyForType(type);
        if (foodBio != null) return foodBio;
        String domesticHab = DomesticHabFixtureAuthority.artKeyForType(type);
        if (domesticHab != null) return domesticHab;
        String stock = obj.stockState == null ? "" : obj.stockState.toLowerCase(Locale.ROOT);
        String label = obj.label == null ? "" : obj.label.toLowerCase(Locale.ROOT);
        if (type.equals(INN_NEWSPAPER_DISPENSER)) return "feature_newspaper_vending";
        if (type.equals(DISCARDED_NEWSPRINT_SOURCE)) return "feature_old_newspaper_source";
        if (type.equals("broadcast-device")) {
            if (stock.contains("pict") || label.contains("pict")) return "feature_broadcast_pict_screen";
            if (stock.contains("tv") || stock.contains("television") || label.contains("television")) return "feature_broadcast_tv";
            return "feature_broadcast_radio";
        }
        if (type.equals("bank-terminal")) return "feature_bank_terminal";
        if (type.equals("bank-vault")) return "feature_bank_vault";
        if (type.equals("bank-alarm-panel")) return "feature_bank_alarm_panel";
        if (type.equals("light-switch")) return "feature_light_switch";
        if (type.equals("light-fixture")) return "feature_light_fixture";
        if (type.equals("planted-explosive")) return "feature_planted_explosive";
        if (type.equals("shop")) return "feature_public_service_counter";
        if (type.equals("governor")) return "feature_public_info_column";
        if (type.equals("faction-journal")) return "feature_public_notice_wall";
        return null;
    }

    static String auditSummary() {
        return "assetIntegrationDiscipline version=" + VERSION + " promotedTypes=" + PROMOTED.size() +
                " legacyAliases=" + LEGACY_TO_CANONICAL.size() + " semanticKeys=" + CANONICAL_TO_SEMANTIC.size() +
                " policy=semantic runtime handles with legacy alias boundary";
    }
}
