package mechanist;

/** Runs the narrow Gate 3 readability checks from one entry point. */
final class Gate3PlayerFacingTextSmokeSuite {
    public static void main(String[] args) throws Exception {
        FactionContractDisplaySmoke.main(args);
        PlayerFacingCopySanitizerSmoke.main(args);
        PlayerFacingUiTextSmoke.main(args);
        PlayerFacingDenialTextSmoke.main(args);
        PlayerFacingInspectionTextSmoke.main(args);
        PlayerFacingActionTextSmoke.main(args);
        PlayerFacingTextWrapSmoke.main(args);
        PlayerFacingPanelBodySmoke.main(args);
        PlayerFacingEventLogTextSmoke.main(args);
        PlayerFacingTooltipTextSmoke.main(args);
        PlayerFacingListRowTextSmoke.main(args);
        PlayerFacingMenuOptionTextSmoke.main(args);
        Gate3PresentationAuditSmoke.main(args);
        Milestone02LookExamineReadabilitySmoke.main(args);
        Milestone02MovementPlanningReadabilitySmoke.main(args);
        Milestone02MovementPlanningDefinitionAuditSmoke.main(args);
        Milestone02MovementPlanningFocusResetSmoke.main(args);
        Milestone02MovementExecutionAuthoritySmoke.main(args);
        Milestone02PauseMovementRecoverySmoke.main(args);
        Milestone02MovementDebugOverlaySmoke.main(args);
        Milestone02QuestObjectiveGuidanceSmoke.main(args);
        Milestone02PetInteractionFeedbackSmoke.main(args);
        Milestone02ActionDenialGuidanceSmoke.main(args);
        Milestone02ConversationReadabilitySmoke.main(args);
        Milestone02ContextPromptReadabilitySmoke.main(args);
        Milestone02InfopediaMechanicsReadabilitySmoke.main(args);
        Milestone02InfopediaHotLinkSmoke.main(args);
        Milestone02MenuUniformityReadabilitySmoke.main(args);
        Milestone02MenuDefinitionAuditSmoke.main(args);
        Milestone02InputRebindingAuditSmoke.main(args);
        Milestone02InputConflictRecoverySmoke.main(args);
        Milestone02CurrentBindingPromptSmoke.main(args);
        Milestone02InputProfilePersistenceSmoke.main(args);
        Milestone02ControllerTuningRuntimeSmoke.main(args);
        Milestone02ControllerTapHoldSmoke.main(args);
        Milestone02ControllerConnectionSmoke.main(args);
        Milestone02ControllerGlyphPromptSmoke.main(args);
        Milestone02ZoneTileSlotStateSmoke.main(args);
        Milestone02ZoneTileLayerMappingSmoke.main(args);
        Milestone02ZoneTilePushSqueezeMovementSmoke.main(args);
        Milestone02DoomHudFacingSmoke.main(args);
        Milestone02TradeReadabilitySmoke.main(args);
        Milestone02InventoryReadabilitySmoke.main(args);
        Milestone02ContainerReadabilitySmoke.main(args);
        Milestone02FactionRosterReadabilitySmoke.main(args);
        Milestone02ProductionReadabilitySmoke.main(args);
        Milestone02ConstructionReadabilitySmoke.main(args);
        Milestone02ConstructionCategorySmoke.main(args);
        Milestone02BodyConditionReadabilitySmoke.main(args);
        Milestone02CharacterPaperDollSmoke.main(args);
        Milestone02CharacterEquipmentMedicalSmoke.main(args);
        Milestone02CharacterEquipmentScreenIntegrationSmoke.main(args);
        Milestone02MedicalTreatmentReadabilitySmoke.main(args);
        Milestone02EntityIdentityReadabilitySmoke.main(args);
        Milestone02ExpansionHeatReadabilitySmoke.main(args);
        Milestone02InteractionApproachSmoke.main(args);
        Milestone02ContractObjectiveReadabilitySmoke.main(args);
        Milestone02TransferWorkflowConsistencySmoke.main(args);
        Milestone02LivePanelPromptSmoke.main(args);
        Milestone02RenderAssetBindingDoctrineSmoke.main(args);
        Milestone02SemanticRenderAssetResolverSmoke.main(args);
        Milestone02SemanticCompiledIndexBoundarySmoke.main(args);
        Milestone02SemanticAssetMigrationCoverageSmoke.main(args);
        PortraitSemanticPartitionResolverSmoke.main(args);
        TileSemanticRuntimeRegistrySmoke.main(args);
        Milestone03ProductionQualityTraceSmoke.main(args);
        Milestone03QualityProvenanceSmoke.main(args);
        Milestone03ProductionOutcomeForecastSmoke.main(args);
        Milestone03MachineConditionProductionSmoke.main(args);
        Milestone03MachineRepairWorkflowSmoke.main(args);
        Milestone03ProductionOperatorSkillSmoke.main(args);
        Milestone03ProductionMaterialQualitySmoke.main(args);
        Milestone03ProductionWorkerQualitySmoke.main(args);
        Milestone03MachineKnowledgeSourceSmoke.main(args);
        Milestone03ProductionBatchProvenanceSmoke.main(args);
        Milestone03ProductionFacilityQualitySmoke.main(args);
        Milestone03ProductionDefectAppraisalSmoke.main(args);
        Milestone03ProductionToolQualitySmoke.main(args);
        OptionsSwingComponentSmoke.main(args);
        System.out.println("Gate 3 player-facing text smoke suite passed.");
    }

    private Gate3PlayerFacingTextSmokeSuite() { }
}
