package mechanist;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.util.Objects;

/**
 * Generated by tools/obfuscation/SensitiveStringTableGenerator.java at 2026-05-22T13:03:00.427238242Z.
 * Source manifest: /mnt/data/mech_obf_work/mech_hp/config/obfuscation/sensitive-strings.properties
 * Do not place raw sensitive security strings in this generated file.
 */
public final class ObfuscatedStringTable {
    private static final int GCM_TAG_BITS = 128;
    private static final byte[] KEY = new byte[]{(byte)-85,(byte)-78,(byte)106,(byte)101,(byte)-78,(byte)-13,(byte)-48,(byte)-2,(byte)96,(byte)-54,(byte)-32,(byte)121,(byte)-95,(byte)66,(byte)-54,(byte)-121,(byte)127,(byte)7,(byte)-103,(byte)-21,(byte)-40,(byte)26,(byte)-41,(byte)93,(byte)-80,(byte)41,(byte)58,(byte)82,(byte)95,(byte)20,(byte)14,(byte)122};

    private ObfuscatedStringTable() { }

    public enum Key {
        REPLAY_ATTACK_OR_DUPLICATE_PACKET,
        SEQUENCE_GAP_EXCEEDS_LIMIT,
        SEQUENCE_GAP_TIMEOUT,
        STATE_DESYNCHRONIZATION_DEFILER_ANOMALIE,
        SUSPICIOUS_AUTOMATION_ACTIVITY
    }

    public static String text(Key key) {
        Objects.requireNonNull(key, "key");
        return switch (key) {
            case REPLAY_ATTACK_OR_DUPLICATE_PACKET -> decode(new byte[]{(byte)-108,(byte)-6,(byte)86,(byte)13,(byte)83,(byte)19,(byte)91,(byte)-105,(byte)122,(byte)-88,(byte)-33,(byte)125}, new byte[]{(byte)65,(byte)6,(byte)47,(byte)-10,(byte)13,(byte)-72,(byte)-63,(byte)122,(byte)-102,(byte)35,(byte)27,(byte)-60,(byte)56,(byte)-119,(byte)-52,(byte)-64,(byte)50,(byte)69,(byte)-118,(byte)14,(byte)-17,(byte)-4,(byte)-50,(byte)-124,(byte)-46,(byte)-16,(byte)57,(byte)78,(byte)0,(byte)110,(byte)43,(byte)-34,(byte)-25,(byte)-102,(byte)-113,(byte)-97,(byte)-94,(byte)32,(byte)-68,(byte)-16,(byte)90,(byte)-125,(byte)-66,(byte)-32,(byte)-70,(byte)34,(byte)95,(byte)-67,(byte)8,(byte)-27,(byte)83,(byte)-43,(byte)23,(byte)104,(byte)59,(byte)73,(byte)-62,(byte)-128});
            case SEQUENCE_GAP_EXCEEDS_LIMIT -> decode(new byte[]{(byte)-125,(byte)8,(byte)82,(byte)-85,(byte)93,(byte)29,(byte)-13,(byte)-30,(byte)-72,(byte)-9,(byte)-58,(byte)-40}, new byte[]{(byte)-128,(byte)30,(byte)-6,(byte)-39,(byte)10,(byte)-36,(byte)-28,(byte)-103,(byte)42,(byte)12,(byte)-36,(byte)-91,(byte)83,(byte)-37,(byte)-29,(byte)123,(byte)94,(byte)-39,(byte)-49,(byte)-34,(byte)3,(byte)-14,(byte)7,(byte)100,(byte)83,(byte)-81,(byte)57,(byte)-63,(byte)-46,(byte)26,(byte)-126,(byte)-15,(byte)-101,(byte)119,(byte)41,(byte)-9,(byte)123,(byte)82,(byte)-7,(byte)-99,(byte)-45,(byte)28});
            case SEQUENCE_GAP_TIMEOUT -> decode(new byte[]{(byte)82,(byte)68,(byte)106,(byte)109,(byte)-7,(byte)-128,(byte)-105,(byte)67,(byte)83,(byte)24,(byte)-66,(byte)-44}, new byte[]{(byte)-52,(byte)-41,(byte)116,(byte)-82,(byte)37,(byte)104,(byte)-62,(byte)-88,(byte)12,(byte)-126,(byte)60,(byte)-111,(byte)69,(byte)123,(byte)75,(byte)119,(byte)-96,(byte)0,(byte)55,(byte)-45,(byte)-4,(byte)-121,(byte)114,(byte)-104,(byte)-115,(byte)-50,(byte)-96,(byte)-124,(byte)-94,(byte)64,(byte)99,(byte)62,(byte)76,(byte)52,(byte)95,(byte)-126});
            case STATE_DESYNCHRONIZATION_DEFILER_ANOMALIE -> decode(new byte[]{(byte)-43,(byte)-119,(byte)78,(byte)32,(byte)-57,(byte)-44,(byte)58,(byte)-3,(byte)-33,(byte)-56,(byte)78,(byte)34}, new byte[]{(byte)-110,(byte)-91,(byte)-60,(byte)-102,(byte)-123,(byte)98,(byte)-13,(byte)5,(byte)77,(byte)118,(byte)121,(byte)-1,(byte)29,(byte)-32,(byte)-108,(byte)17,(byte)117,(byte)-31,(byte)5,(byte)4,(byte)31,(byte)71,(byte)-5,(byte)-123,(byte)-12,(byte)52,(byte)96,(byte)-85,(byte)-119,(byte)70,(byte)15,(byte)-16,(byte)-121,(byte)27,(byte)-82,(byte)61,(byte)124,(byte)-122,(byte)87,(byte)-37,(byte)-20,(byte)-110,(byte)103,(byte)1,(byte)-27,(byte)70,(byte)45,(byte)-79,(byte)-19,(byte)-28,(byte)27,(byte)81,(byte)-32,(byte)4,(byte)17,(byte)77});
            case SUSPICIOUS_AUTOMATION_ACTIVITY -> decode(new byte[]{(byte)-97,(byte)25,(byte)-50,(byte)25,(byte)103,(byte)-47,(byte)101,(byte)-78,(byte)33,(byte)-126,(byte)-46,(byte)-48}, new byte[]{(byte)66,(byte)90,(byte)-98,(byte)69,(byte)-96,(byte)-32,(byte)96,(byte)88,(byte)-64,(byte)-103,(byte)32,(byte)80,(byte)-27,(byte)-64,(byte)96,(byte)-108,(byte)-117,(byte)114,(byte)116,(byte)116,(byte)-127,(byte)-120,(byte)-92,(byte)-6,(byte)-63,(byte)15,(byte)-47,(byte)-6,(byte)49,(byte)-11,(byte)122,(byte)-111,(byte)-120,(byte)-7,(byte)-44,(byte)27,(byte)-26,(byte)-95,(byte)-68,(byte)62,(byte)-12,(byte)-107,(byte)-65,(byte)108,(byte)33,(byte)50});
        };
    }

    private static String decode(byte[] iv, byte[] encrypted) {
        try {
            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(KEY, "AES"), new GCMParameterSpec(GCM_TAG_BITS, iv));
            byte[] plain = cipher.doFinal(encrypted);
            return new String(plain, StandardCharsets.UTF_8);
        } catch (GeneralSecurityException ex) {
            throw new IllegalStateException("Encoded string table failed integrity validation", ex);
        }
    }
}
