#The Mechanist EULA consent state
#Thu May 28 15:32:01 AKDT 2026
eula.acceptedAt=2026-05-28T23\:32\:01.822268400Z
eula.version=eula-consent-authority-0.9.10ip
eula_consented=true
profile.id=MECH-67EC1CCAD37A5
profile.provider=Internal
