#The Mechanist persistent options
#Sat Jun 13 22:41:45 AKDT 2026
anchorPointSnapping=true
artQualityIndex=0
autoLootEnabled=false
blueprintCaptureTool=true
blueprintPreflightChecklist=true
bootSound=true
color0=15201023
color1=13952758
color2=10270928
color3=16757854
color4=329739
colorPreset=5
colorTarget=1
constructionTrapWarnings=true
conversationSound=false
conversationVolume=80
cvdModeIndex=0
diagnosticsOverlay=false
displayResolutionPolicyVersion=highest-detected-on-launch-0.9.10jn
doomFogModeIndex=0
doomModeEnabled=false
doomModeFovDegrees=80
downscaleIndex=0
economicDisruptionAlerts=true
favoredItemProtection=true
fontScale=105
generatedAssetPayloadRoot=
ghostRoomStamps=true
globalScarcityWarnings=true
highContrastText=false
holdToRepeatConstruction=true
hollowBoxTool=true
hoverHelp=true
importedPortraits=true
instantDialogueText=false
invalidPlacementDiagnostics=true
isFrameLimited=true
itemSafetyProfileIndex=1
lightingFxIndex=2
localGlobalPriceHints=true
lowQualityPickupWarnings=true
machineOutputAutoRouting=true
mapTileSizeIndex=2
materialSubstitutionPrompts=true
musicEnabled=true
musicVolume=20
namedDeathAlerts=true
noMixedQualityStacking=true
omniDirectionalGhostBuild=true
productionBlockerWarnings=true
proxyCraftingFromLinkedStorage=true
recipeHudPinning=true
reducedMotion=true
renderQualityIndex=2
resolutionIndex=13
resolutionUserSelected=true
resourceEstimateTooltips=true
safeWorkerPriorities=true
screenSaver=true
screenShakePercent=100
sfxVolume=80
singlePlayerTickModeIndex=0
skipRepeatLogoSplashes=true
smartStorageFilters=true
soundEnabled=true
standaloneBlueprintSandbox=true
subtitlesEnabled=true
targetFpsIndex=0
textDensityPolicyVersion=compact-text-0.9.10it
tileIconRendering=true
uiScale=140
underAttackSupplyLock=true
windowMode=2
worldZoomIndex=3
