#The Mechanist persistent options
#Thu May 28 17:14:06 AKDT 2026
anchorPointSnapping=true
artQualityIndex=0
autoLootEnabled=false
blueprintCaptureTool=true
blueprintPreflightChecklist=true
bootSound=true
color0=13154436
color1=14470545
color2=10523760
color3=15454328
color4=526346
colorPreset=0
colorTarget=1
constructionTrapWarnings=true
conversationSound=true
conversationVolume=80
cvdModeIndex=0
diagnosticsOverlay=false
displayResolutionPolicyVersion=highest-detected-on-launch-0.9.10jn
doomFogModeIndex=0
doomModeEnabled=false
doomModeFovDegrees=80
downscaleIndex=0
economicDisruptionAlerts=true
favoredItemProtection=true
fontScale=90
generatedAssetPayloadRoot=
ghostRoomStamps=true
globalScarcityWarnings=true
highContrastText=true
holdToRepeatConstruction=true
hollowBoxTool=true
hoverHelp=true
importedPortraits=true
instantDialogueText=false
invalidPlacementDiagnostics=true
isFrameLimited=true
itemSafetyProfileIndex=1
lightingFxIndex=2
localGlobalPriceHints=true
lowQualityPickupWarnings=true
machineOutputAutoRouting=true
mapTileSizeIndex=1
materialSubstitutionPrompts=true
musicEnabled=true
musicVolume=70
namedDeathAlerts=true
noMixedQualityStacking=true
omniDirectionalGhostBuild=true
productionBlockerWarnings=true
proxyCraftingFromLinkedStorage=true
recipeHudPinning=true
reducedMotion=true
renderQualityIndex=2
resolutionIndex=104
resolutionUserSelected=false
resourceEstimateTooltips=true
safeWorkerPriorities=true
screenSaver=true
screenShakePercent=100
sfxVolume=80
skipRepeatLogoSplashes=true
smartStorageFilters=true
soundEnabled=true
standaloneBlueprintSandbox=true
subtitlesEnabled=true
targetFpsIndex=2
textDensityPolicyVersion=compact-text-0.9.10it
tileIconRendering=true
uiScale=145
underAttackSupplyLock=true
windowMode=1
worldZoomIndex=0
