#The Mechanist fallback local profile
#Wed Jun 03 21:02:57 AKDT 2026
profile.cvdMode=Normal
profile.diagnosticsOverlay=false
profile.hardwareSignature=HW-27F841AFC3427E915724
profile.id=MECH-PROFILE-CBA6F5E9E7EC
profile.initialRamMb=1024
profile.internalHeight=270
profile.internalWidth=480
profile.isLegalAdult=false
profile.lastSyncedIso=2026-06-04T05\:02\:57.669758400Z
profile.maxRamMb=4096
profile.name=Operator E0175DF4
profile.portraitIndex=0
profile.runtimeTarget=CLIENT_GRAPHICS
profile.schema=fallback-local-profile-v1
profile.version=0.9.10hn
profile.wrapperDetected=false
profile.wrapperProvider=Internal
