#!/usr/bin/env python3
from __future__ import annotations

import csv, json, re
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GAMEPANEL = ROOT / "src" / "mechanist" / "GamePanel.java"
OUT_JSON = ROOT / "docs" / "gamepanel_method_index.json"
OUT_TSV = ROOT / "docs" / "gamepanel_method_index.tsv"
OUT_MD = ROOT / "docs" / "gamepanel_extraction_targets.md"
METHOD_RE = re.compile(r"(?P<prefix>\b(?:public|protected|private|static|final|synchronized|abstract|native|strictfp|default)\b[\w\s<>,\[\].?@]*|[A-Za-z_$][\w\s<>,\[\].?@]*)\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*\([^;{}]*\)\s*(?:throws\s+[\w\s,.<>]+)?\{")
CONTROL = {"if", "for", "while", "switch", "catch", "try", "do", "else", "synchronized", "new"}

@dataclass
class Method:
    name: str
    start_line: int
    end_line: int
    line_count: int
    priority: str
    recommendation: str


def mask(text: str) -> str:
    c = list(text); i = 0; n = len(c)
    while i < n:
        ch = c[i]; nx = c[i+1] if i+1 < n else ""
        if ch == "/" and nx == "/":
            while i < n and c[i] != "\n": c[i] = " "; i += 1
            continue
        if ch == "/" and nx == "*":
            c[i] = c[i+1] = " "; i += 2
            while i+1 < n and not (c[i] == "*" and c[i+1] == "/"):
                if c[i] not in "\r\n": c[i] = " "
                i += 1
            if i+1 < n: c[i] = c[i+1] = " "; i += 2
            continue
        if ch in ('"', "'"):
            q = ch; c[i] = " "; i += 1; esc = False
            while i < n:
                cur = c[i]
                if cur not in "\r\n": c[i] = " "
                if esc: esc = False
                elif cur == "\\": esc = True
                elif cur == q: i += 1; break
                i += 1
            continue
        i += 1
    return "".join(c)


def starts(text: str) -> list[int]:
    s = [0]
    for i, ch in enumerate(text):
        if ch == "\n": s.append(i+1)
    return s


def line_no(s: list[int], pos: int) -> int:
    lo, hi = 0, len(s)-1
    while lo <= hi:
        mid = (lo+hi)//2
        if s[mid] <= pos: lo = mid+1
        else: hi = mid-1
    return hi+1


def depths(text: str) -> list[int]:
    d = 0; out = [0]*len(text)
    for i,ch in enumerate(text):
        out[i] = d
        if ch == "{": d += 1
        elif ch == "}": d = max(0, d-1)
    return out


def close_brace(text: str, pos: int) -> int:
    d = 0
    for i in range(pos, len(text)):
        if text[i] == "{": d += 1
        elif text[i] == "}":
            d -= 1
            if d == 0: return i
    raise RuntimeError("unclosed method brace")


def rec(name: str, lines: int) -> tuple[str, str]:
    n = name.lower()
    if name in {"drawOptions", "drawIntroCrawl", "drawGame", "panelLines", "handleKeyPressed", "mouseClicked", "rebuildButtons"}:
        return "immediate", "first seam extraction target"
    if lines >= 160:
        return "high", "oversized method; split after first seam pass"
    if lines >= 80:
        return "medium", "large method; inspect after high-priority seams"
    if n.startswith("draw"):
        return "render", "render helper candidate"
    return "normal", "leave until owning subsystem is clearer"


def main() -> int:
    if not GAMEPANEL.exists(): raise SystemExit(f"Missing {GAMEPANEL}")
    text = GAMEPANEL.read_text(encoding="utf-8", errors="replace")
    m = mask(text); s = starts(text); dep = depths(m); methods: list[Method] = []
    for hit in METHOD_RE.finditer(m):
        if dep[hit.start()] != 1: continue
        name = hit.group("name")
        if name in CONTROL: continue
        ob = m.find("{", hit.start())
        cb = close_brace(m, ob)
        st = line_no(s, hit.start()); en = line_no(s, cb); cnt = en-st+1
        p, r = rec(name, cnt)
        methods.append(Method(name, st, en, cnt, p, r))
    methods.sort(key=lambda x: (-x.line_count, x.start_line))
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps({"schema":"mechanist.gamepanel_method_index.v1","time":datetime.now(timezone.utc).isoformat(),"source":str(GAMEPANEL),"method_count":len(methods),"methods":[asdict(x) for x in methods]}, indent=2), encoding="utf-8")
    with OUT_TSV.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["name","start_line","end_line","line_count","priority","recommendation"], delimiter="\t", lineterminator="\n")
        w.writeheader(); [w.writerow(asdict(x)) for x in methods]
    lines = ["# GamePanel Extraction Targets", "", "Generated by `ROOT_tools/gamepanel_method_indexer.py`.", "", "## Immediate targets", ""]
    lines.append("| Method | Lines | Location | Recommendation |")
    lines.append("|---|---:|---|---|")
    for x in sorted([m for m in methods if m.priority == "immediate"], key=lambda y: y.start_line):
        lines.append(f"| `{x.name}` | {x.line_count} | {x.start_line}-{x.end_line} | {x.recommendation} |")
    lines += ["", "## Largest methods", "", "| Method | Lines | Location | Priority |", "|---|---:|---|---|"]
    for x in methods[:25]:
        lines.append(f"| `{x.name}` | {x.line_count} | {x.start_line}-{x.end_line} | {x.priority} |")
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Indexed GamePanel methods: {len(methods)}")
    print(f"Wrote {OUT_TSV}")
    print(f"Wrote {OUT_JSON}")
    print(f"Wrote {OUT_MD}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
