#The Mechanist fallback local profile
#Thu May 28 15:31:59 AKDT 2026
profile.cvdMode=Normal
profile.diagnosticsOverlay=false
profile.hardwareSignature=HW-27F841AFC3427E915724
profile.id=MECH-PROFILE-EFA1BA24BD22
profile.initialRamMb=1024
profile.internalHeight=270
profile.internalWidth=480
profile.isLegalAdult=false
profile.lastSyncedIso=2026-05-28T23\:31\:59.900349100Z
profile.maxRamMb=4096
profile.name=Operator D37A5476
profile.portraitIndex=0
profile.runtimeTarget=CLIENT_GRAPHICS
profile.schema=fallback-local-profile-v1
profile.version=0.9.10hn
profile.wrapperDetected=false
profile.wrapperProvider=Internal
