#The Mechanist fallback local profile
#Fri May 22 10:59:45 UTC 2026
profile.cvdMode=Normal
profile.diagnosticsOverlay=false
profile.hardwareSignature=HW-93D12D0AE16235AB2292
profile.id=MECH-PROFILE-A3691CB189EE
profile.initialRamMb=1024
profile.internalHeight=270
profile.internalWidth=480
profile.isLegalAdult=true
profile.lastSyncedIso=2026-05-22T10\:59\:45.430634427Z
profile.maxRamMb=4096
profile.name=Operator B3A00922
profile.portraitIndex=0
profile.runtimeTarget=CLIENT_GRAPHICS
profile.schema=fallback-local-profile-v1
profile.version=0.9.10hn
profile.wrapperDetected=false
profile.wrapperProvider=Internal
