#The Mechanist JVM runtime profile
mode=CLIENT_GRAPHICS
runtimeTarget=CLIENT_GRAPHICS
pipeline=OS_ACCELERATED
initialRamMb=1024
maxRamMb=4096
gc=Z_GC
stringDeduplication=true
transparentAcceleration=true
forceVolatileVram=true
disableVectorAntialiasing=false
manualOverrides=
