#The Mechanist EULA consent state
#Sat May 23 07:36:55 UTC 2026
eula.acceptedAt=2026-05-23T07\:36\:55.592716887Z
eula.version=eula-consent-authority-0.9.10ip
eula_consented=true
profile.id=MECH-7A4BA372B3A00
profile.provider=Internal
