import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;

/**
 * Recursively indexes The Mechanist asset tree and writes a readable Markdown manifest.
 *
 * <p>Run from the repository root with:</p>
 * <pre>java tools.AssetManifestGenerator</pre>
 *
 * <p>Optional arguments:</p>
 * <pre>java tools.AssetManifestGenerator [assetRoot] [outputMarkdown]</pre>
 */
public final class AssetManifestGenerator {
    private static final Path DEFAULT_ASSET_ROOT = Paths.get("assets");
    private static final Path DEFAULT_OUTPUT = Paths.get("docs", "ASSET_MANIFEST.md");

    private static final List<String> RISKY_TERMS = List.of(
            "adeptus",
            "arbites",
            "astartes",
            "mechanicus",
            "imperium",
            "imperial",
            "emperor",
            "genestealer",
            "tyranid",
            "xenos",
            "chaos",
            "inquisition",
            "inquisitor",
            "ordo",
            "bolter",
            "lasgun",
            "servitor",
            "servo skull",
            "servo_skull",
            "tech priest",
            "tech_priest",
            "space marine",
            "space_marine",
            "warhammer",
            "40k"
    );

    private AssetManifestGenerator() { }

    public static void main(String[] args) throws IOException {
        Path assetRoot = args.length >= 1 ? Paths.get(args[0]) : DEFAULT_ASSET_ROOT;
        Path output = args.length >= 2 ? Paths.get(args[1]) : DEFAULT_OUTPUT;

        if (!Files.exists(assetRoot)) {
            throw new IOException("Asset root does not exist: " + assetRoot.toAbsolutePath());
        }
        if (!Files.isDirectory(assetRoot)) {
            throw new IOException("Asset root is not a directory: " + assetRoot.toAbsolutePath());
        }

        List<AssetEntry> entries = scan(assetRoot);
        String markdown = render(assetRoot, entries);

        Path parent = output.toAbsolutePath().getParent();
        if (parent != null) Files.createDirectories(parent);
        Files.writeString(output, markdown, StandardCharsets.UTF_8);
    }

    private static List<AssetEntry> scan(Path assetRoot) throws IOException {
        List<AssetEntry> entries = new ArrayList<>();
        try (Stream<Path> stream = Files.walk(assetRoot)) {
            stream.filter(Files::isRegularFile)
                    .sorted(Comparator.comparing(path -> normalize(assetRoot.relativize(path))))
                    .forEach(path -> entries.add(AssetEntry.from(assetRoot, path)));
        }
        return entries;
    }

    private static String render(Path assetRoot, List<AssetEntry> entries) {
        List<AssetEntry> flagged = entries.stream().filter(entry -> !entry.riskyTerms.isEmpty()).toList();
        Map<String, Integer> byExtension = new TreeMap<>();
        for (AssetEntry entry : entries) {
            byExtension.merge(entry.extension, 1, Integer::sum);
        }

        StringBuilder out = new StringBuilder();
        out.append("# Asset Manifest\n\n");
        out.append("Generated by `tools/AssetManifestGenerator.java`.\n\n");
        out.append("- Generated at: `").append(Instant.now()).append("`\n");
        out.append("- Asset root: `").append(normalize(assetRoot)).append("`\n");
        out.append("- Total files: ").append(entries.size()).append("\n");
        out.append("- Files with risky IP terms: ").append(flagged.size()).append("\n\n");

        out.append("## Risky IP Term Findings\n\n");
        if (flagged.isEmpty()) {
            out.append("No risky IP terms were detected in asset paths.\n\n");
        } else {
            out.append("| Asset path | Terms |\n");
            out.append("| --- | --- |\n");
            for (AssetEntry entry : flagged) {
                out.append("| `").append(entry.relativePath).append("` | ")
                        .append(String.join(", ", entry.riskyTerms)).append(" |\n");
            }
            out.append('\n');
        }

        out.append("## File Counts by Extension\n\n");
        out.append("| Extension | Count |\n");
        out.append("| --- | ---: |\n");
        for (Map.Entry<String, Integer> entry : byExtension.entrySet()) {
            out.append("| `").append(entry.getKey()).append("` | ").append(entry.getValue()).append(" |\n");
        }
        out.append('\n');

        out.append("## Full Asset Path Inventory\n\n");
        for (AssetEntry entry : entries) {
            out.append("- `").append(entry.relativePath).append("`\n");
        }
        return out.toString();
    }

    private static String normalize(Path path) {
        return path.toString().replace('\\', '/');
    }

    private record AssetEntry(String relativePath, String extension, List<String> riskyTerms) {
        static AssetEntry from(Path assetRoot, Path file) {
            String relative = normalize(assetRoot.relativize(file));
            return new AssetEntry(relative, extensionOf(relative), riskyTermsIn(relative));
        }
    }

    private static String extensionOf(String relativePath) {
        int slash = relativePath.lastIndexOf('/');
        int dot = relativePath.lastIndexOf('.');
        if (dot <= slash || dot == relativePath.length() - 1) return "[none]";
        return relativePath.substring(dot + 1).toLowerCase(Locale.ROOT);
    }

    private static List<String> riskyTermsIn(String relativePath) {
        String lower = relativePath.toLowerCase(Locale.ROOT);
        List<String> found = new ArrayList<>();
        for (String term : RISKY_TERMS) {
            if (lower.contains(term)) found.add(term);
        }
        return found;
    }
}
